.editorconfig
CONTRIBUTING.md
README.md
pom.xml

See other guidelines for you to follow:
https://dev.folio.org/guidelines/create-new-repo/

FOLIO-722 initial repo setup

---

pom.xml
src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/java/org/folio/search/service/metadata/SearchFieldProvider.java
src/main/resources/model/instance.json
src/main/resources/swagger.api/examples/indexRecordResponse.sample
src/main/resources/swagger.api/examples/searchResult.sample
src/main/resources/swagger.api/mod-search.yaml
src/main/resources/swagger.api/schemas/instance.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java
src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java
src/test/java/org/folio/search/support/base/BaseIntegrationTest.java

- Implement source fields
- Update swagger documentation
- Update integration tests

MSEARCH-18 Implement search by publishers

---

src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java
src/main/java/org/folio/search/model/metadata/ResourceDescription.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/java/org/folio/search/service/metadata/MetadataResourceProvider.java
src/main/resources/model/instance.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/model/metadata/ResourceDescriptionTest.java
src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java

https://issues.folio.org/browse/MSEARCH-17 - Instance - support contributors keyword search

MSEARCH-17: Allow multilang search for contributors.name property.

---

src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java
src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java
src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java
src/main/java/org/folio/search/service/es/SearchMappingsHelper.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/java/org/folio/search/service/metadata/SearchFieldProvider.java
src/main/java/org/folio/search/service/setter/instance/PublicNotesProcessor.java
src/main/java/org/folio/search/utils/SearchUtils.java
src/main/resources/model/instance.json
src/main/resources/swagger.api/schemas/instance.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java
src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java
src/test/java/org/folio/search/service/setter/instance/PublicNotesProcessorTest.java
src/test/java/org/folio/search/utils/SearchConverterUtilsTest.java
src/test/java/org/folio/search/utils/TestUtils.java
src/test/resources/samples/semantic_web_primer.json

- Implement search by multi-language search fields
- Add unit tests for such cases
- Implement search by notes.note field where staffOnly equals to false

MSEARCH-21 Implement search by public notes

---

descriptors/ModuleDescriptor-template.json

increase memory limit mod-search, see FOLIO-2973.

bump docker memory limit mod-search

---

src/main/java/org/folio/search/client/PermissionsClient.java
src/main/java/org/folio/search/client/UsersClient.java
src/main/java/org/folio/search/model/service/ResultList.java
src/main/java/org/folio/search/service/TenantScopedExecutionService.java
src/main/java/org/folio/search/service/systemuser/SystemUserService.java
src/test/java/org/folio/search/client/PermissionsClientTest.java
src/test/java/org/folio/search/client/cql/CqlQueryTest.java
src/test/java/org/folio/search/integration/ResourceFetchServiceTest.java
src/test/java/org/folio/search/service/systemuser/SystemUserServiceTest.java

Fixes:
* Rename field "permissions" (src/main/java/org/folio/search/client/PermissionsClient.java)
* Rename field "users" (src/main/java/org/folio/search/client/UsersClient.java)
* Define and throw a dedicated exception instead of using a generic one (src/main/java/org/folio/search/service/TenantScopedExecutionService.java)
* Use assertThat(actual).hasToString(expectedString) instead (src/test/java/org/folio/search/client/cql/CqlQueryTest.java)
* Refactor the code of the lambda to have only one invocation possibly throwing a runtime exception (src/test/java/org/folio/search/service/systemuser/SystemUserServiceTest.java)

Fix code smells on master.

---

src/test/java/org/folio/search/controller/SearchInstanceIT.java

Word match in following Inventory Instance fields:
* series (array of strings)
* identifiers (all) (array of objects)
* electronicAccess (array of objects)

MSEARCH-1: Add tests to verify search.

---

src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java
src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java
src/main/java/org/folio/search/service/converter/ElasticsearchHitConverter.java
src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java
src/main/java/org/folio/search/service/es/SearchMappingsHelper.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/java/org/folio/search/utils/SearchUtils.java
src/main/resources/elasticsearch/index-field-types.json
src/test/java/org/folio/search/controller/ConfigControllerIT.java
src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java
src/test/java/org/folio/search/service/converter/ElasticsearchHitConverterTest.java
src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java
src/test/java/org/folio/search/service/es/SearchMappingsHelperTest.java
src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java
src/test/java/org/folio/search/utils/SearchUtilsTest.java

- Contains breaking changes and reindex is required after merging this PR

MSEARCH-91 Implement plain fields for multilang values

---

pom.xml

Upgrade Spring Boot version to latest 2.4.4
Upgrade Spring Cloud:Feign to latest 3.0.2

MSEARCH-98: Upgrade Spring Boot and Feign versions to latest.

---

src/main/java/org/folio/search/configuration/KafkaConfiguration.java
src/main/java/org/folio/search/configuration/properties/FolioKafkaProperties.java
src/main/resources/application.yml
src/test/java/org/folio/search/configuration/KafkaConfigurationTest.java

Increase retry period to 20 seconds

MSEARCH-86: Increase retry period.

---

README.md

Add readme about on-premise ES config and recommended production configuration.

MSEARCH-127: Describe on-premise ES configuration in readme.

---

README.md

The list of available must be clear and documented
All implemented facets are documented in the README.md file

MSEARCH-133 Document list of available facets

---

NEWS.md
README.md
pom.xml
src/main/java/org/folio/search/configuration/KafkaConfiguration.java
src/main/java/org/folio/search/configuration/properties/FolioEnvironment.java
src/main/java/org/folio/search/configuration/properties/FolioKafkaProperties.java
src/main/java/org/folio/search/configuration/properties/OkapiConfigurationProperties.java
src/main/java/org/folio/search/controller/FolioTenantController.java
src/main/java/org/folio/search/integration/KafkaMessageListener.java
src/main/java/org/folio/search/service/KafkaAdminService.java
src/main/java/org/folio/search/service/systemuser/SystemUserService.java
src/main/java/org/folio/search/utils/SearchUtils.java
src/main/resources/application.yml
src/test/java/org/folio/search/configuration/FolioKafkaPropertiesTest.java
src/test/java/org/folio/search/configuration/properties/FolioEnvironmentTest.java
src/test/java/org/folio/search/controller/FolioTenantControllerTest.java
src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java
src/test/java/org/folio/search/repository/IndexRepositoryTest.java
src/test/java/org/folio/search/service/IndexServiceTest.java
src/test/java/org/folio/search/service/KafkaAdminServiceTest.java
src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java
src/test/java/org/folio/search/support/api/InventoryApi.java
src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
src/test/java/org/folio/search/utils/TestConstants.java
src/test/java/org/folio/search/utils/TestUtils.java
src/test/resources/application.yml

Release version 1.3.1 contains important changes for shared deployments with Elasticsearch and Apache Kafka, such as topic names and consumer groups with environment prefix, also Elasticsearch index names with an environment variable prefix.

Release 1.3.1

---

README.md

Add to the documentation the newly implemented search options, such as searching by public and all notes for instances,items and holding-records

MSEARCH-117 Update README.md

---

README.md
src/main/java/org/folio/search/service/setter/item/ItemIdentifiersProcessor.java
src/main/resources/model/instance.json
src/main/resources/swagger.api/schemas/item.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/resources/samples/semantic-web-primer/items.json

Additional for https://github.com/folio-org/mod-search/pull/110
Added support for accessionNumber

MSEARCH-153 Add Identifiers accessionNumber search option for items

---

README.md
src/main/resources/model/authority.json
src/test/java/org/folio/search/controller/SearchAuthorityIT.java

The purpose of this story is to support Authority record search by authority by keyword
[MSEARCH-238](https://issues.folio.org/browse/MSEARCH-238)

MSEARCH-238 Keyword search option

---

src/main/java/org/folio/search/service/SearchService.java
src/test/java/org/folio/search/service/SearchServiceTest.java

This issue remains after the latest pull request, so these changes must fix it

Fix potential NPE issue in sonarcloud

---

src/main/resources/swagger.api/mod-search.yaml
src/test/java/org/folio/search/support/base/ApiEndpoints.java

Fix invalid call-number browsing endpoint.
- Fix endpoint in openapi description and for integration tests

MSEARCH-253 Fix endpoint for call-number browsing

---

README.md
descriptors/DeploymentDescriptor-template.json

Mention server.port in documentation. Fix deployment descriptor.

Listening port property MSEARCH-267

---

README.md
src/main/resources/model/instance.json
src/main/resources/swagger.api/schemas/holding.json
src/main/resources/swagger.api/schemas/item.json
src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java

Implemented filtering on the item\holding record Date updated\created similar to what has been implemented on the instance record.

MSEARCH-222 Filter item\holding by updated date\create date

---

README.md
src/main/resources/model/authority.json
src/test/java/org/folio/search/controller/SearchAuthorityFilterIT.java
src/test/java/org/folio/search/controller/SearchAuthorityIT.java

[MSEARCH-287](https://issues.folio.org/browse/MSEARCH-287)

MSEARCH-287 Create a Subject heading/thesaurus facet

---

src/main/resources/model/authority.json
src/main/resources/swagger.api/schemas/authority.json
src/test/java/org/folio/search/controller/AuthorityBrowseIT.java
src/test/java/org/folio/search/controller/IndexingIT.java
src/test/java/org/folio/search/controller/SearchAuthorityFilterIT.java
src/test/java/org/folio/search/controller/SearchAuthorityIT.java
src/test/java/org/folio/search/controller/SortAuthorityIT.java
src/test/java/org/folio/search/integration/KafkaMessageListenerTest.java
src/test/java/org/folio/search/service/converter/preprocessor/AuthorityEventPreProcessorTest.java
src/test/java/org/folio/search/service/setter/authority/HeadingRefProcessorTest.java

MSEARCH-303 Remove unused search fields

MSEARCH-303 Remove unused search fields

---

src/main/java/org/folio/search/service/browse/AbstractBrowseService.java
src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java
src/test/java/org/folio/search/controller/AuthorityBrowseIT.java
src/test/java/org/folio/search/controller/SubjectBrowseIT.java

Previous value for authority/subject browsing is calculated is incorrectly
- Fix an issue
- Add integration tests for subject/authority to check fixed value

MSEARCH-342 Fix an issue for prev value when browsing around

---

src/main/java/org/folio/search/service/setter/instance/IssnProcessor.java
src/test/java/org/folio/search/service/setter/instance/IssnProcessorTest.java
src/test/java/org/folio/search/utils/TestConstants.java
src/test/resources/mappings/inventory.json

Add Linking ISSN to identifier-types search
https://issues.folio.org/browse/MSEARCH-341

MSEARCH-341 ISSN search: Include Linking ISSN in search

---

src/test/java/org/folio/search/controller/StreamResourceIdsIT.java

It looks like all task was already implemented in [MSEARCH-350](https://github.com/folio-org/mod-search/pull/272) pull request. So I just added unit tests to prove it
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

MSEARCH-349 Change Instance ids stream API to use jobs

---

pom.xml
src/main/java/org/folio/search/service/converter/ElasticsearchDocumentConverter.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/resources/model/authority.json
src/main/resources/model/instance.json
src/test/java/org/folio/search/controller/ConfigIT.java
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/service/converter/ElasticsearchDocumentConverterTest.java
src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java
src/test/resources/samples/semantic-web-primer/holdings.json
src/test/resources/samples/semantic-web-primer/items.json

- Remove optional fields from `_source`

MSEARCH-405 mod-search: investigate options to optimize reindex time

---

NEWS.md
PERSONAL_DATA_DISCLOSURE.md

Place a copy of the [personal data disclosure form](https://github.com/folio-org/personal-data-disclosure/blob/master/PERSONAL_DATA_DISCLOSURE.md) at the top level of the module github repository and check the boxes that apply.
See https://github.com/folio-org/personal-data-disclosure for details.
- Add PERSONAL_DATA_DISCLOSURE.md file
- Update NEWS.md

MSEARCH-402 Add personal data disclosure form

---

NEWS.md
pom.xml
src/main/java/org/folio/search/controller/BrowseController.java
src/main/java/org/folio/search/service/ResourceIdService.java
src/main/java/org/folio/search/service/ResourceIdsJobService.java
src/main/java/org/folio/search/service/TenantScopedExecutionService.java
src/main/java/org/folio/search/service/setter/instance/UniformTitleProcessor.java
src/main/java/org/folio/search/service/systemuser/PrepareSystemUserService.java
src/test/java/org/folio/search/service/converter/ElasticsearchDocumentConverterTest.java
src/test/java/org/folio/search/service/setter/instance/UniformTitleProcessorTest.java

_Upgrade to folio-spring-base v5.0.0

MSEARCH-442 Upgrade to folio-spring-base v5.0.0

---

doc/development.md
src/main/resources/application.yml

Fix ENV variable in application properties

Fix ENV variable in application properties

---

src/main/java/org/folio/search/model/index/SearchDocumentBody.java
src/main/java/org/folio/search/repository/AbstractResourceRepository.java
src/main/java/org/folio/search/repository/InstanceContributorsRepository.java
src/main/java/org/folio/search/repository/InstanceSubjectRepository.java
src/main/java/org/folio/search/repository/SearchRepository.java
src/main/java/org/folio/search/service/es/SearchMappingsHelper.java
src/test/java/org/folio/search/controller/BrowseContributorIT.java
src/test/java/org/folio/search/controller/BrowseSubjectIT.java
src/test/java/org/folio/search/controller/ConfigIT.java
src/test/java/org/folio/search/controller/IndexingIT.java
src/test/java/org/folio/search/controller/SearchAuthorityIT.java
src/test/java/org/folio/search/repository/InstanceSubjectRepositoryTest.java
src/test/java/org/folio/search/repository/SearchRepositoryTest.java
src/test/java/org/folio/search/service/es/SearchMappingsHelperTest.java

MSEARCH-441 Use default routing

---

NEWS.md
pom.xml

Release **v1.8.0**
https://issues.folio.org/browse/MSEARCH-438

Tmp release 1.8.0

---

NEWS.md
pom.xml
src/main/java/org/folio/search/service/converter/ElasticsearchDocumentConverter.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/resources/model/authority.json
src/main/resources/model/instance.json
src/test/java/org/folio/search/controller/ConfigControllerIT.java
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/service/converter/ElasticsearchDocumentConverterTest.java
src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java
src/test/resources/samples/semantic-web-primer/holdings.json
src/test/resources/samples/semantic-web-primer/items.json

Include MSEARCH-405 to make contributors index "keyword"
(cherry picked from commit f802d71990de3ea452565073f1133a79511d71b2)
https://issues.folio.org/browse/MSEARCH-457

MSEARCH-457: make contributors index "keyword"

---

NEWS.md
pom.xml

_Describe the purpose of the pull request._
_How does this change fulfill the purpose?_
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

Bugfix release 1.7.7

---

src/main/java/org/folio/search/cql/builders/AllTermQueryBuilder.java
src/main/resources/elasticsearch/index/authority.json
src/main/resources/elasticsearch/index/instance.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/resources/samples/semantic-web-primer/instance.json

Add char_filter
https://issues.folio.org/browse/MSEARCH-466

MSEARCH-466 Add char_filter for indexes

---

src/main/java/org/folio/search/cql/builders/AllTermQueryBuilder.java
src/main/resources/elasticsearch/index/authority.json
src/main/resources/elasticsearch/index/instance.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java

Change logic of splitting term to words

MSEARCH-466 Change logic on keyword search

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.md
src/main/resources/swagger.api/mod-search.yaml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MSEARCH-5297 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

descriptors/ModuleDescriptor-template.json

add required permissions to tenant interface

fix(consortium): add required permissions to tenant interface

---

src/main/java/org/folio/search/service/ResourceService.java
src/main/java/org/folio/search/service/ScriptService.java
src/main/resources/application.yml

Fix contributors not being indexed
[MSEARCH-551](https://issues.folio.org/browse/MSEARCH-551)
Save stored elasticsearch scripts even if they exist

fix(consortium) Fix contributors not being indexed

---

src/main/java/org/folio/search/service/IndexService.java
src/test/java/org/folio/search/service/IndexServiceTest.java

- Ignore "recreateIndex" for consortium member tenants

fix(consortium): Don't recreate index for consortium member tenants

---

src/main/java/org/folio/search/utils/CallNumberUtils.java

Avoid NPE which is being thrown while browsing call numbers (all) using one letter (s)
Checked for null before further processing
[MSEARCH-557](https://issues.folio.org/browse/MSEARCH-557)

MSEARCH-557: Added changes to avoid NPE

---

src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java
src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java

Fix browsing with/without suffix
Compare anchor to both shelving order with/without suffix

fix(cn-browse): Fix browsing with/without suffix

---

pom.xml
src/main/java/org/folio/search/utils/CallNumberUtils.java
src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
src/test/java/org/folio/search/utils/CallNumberUtilsTest.java

Fix typed call numbers with suffix not shown
[MSEARCH-599](https://issues.folio.org/browse/MSEARCH-599)
- Fix browse item and instance item full call number comparison

fix(cn-browse): Fix typed call numbers with suffix not shown

---

NEWS.md
PULL_REQUEST_TEMPLATE.md
descriptors/ModuleDescriptor-template.json
pom.xml

upgrade to folio-spring-support v7.2.1
https://issues.folio.org/browse/MSEARCH-633

fix: upgrade to folio-spring-support v7.2.1

---

pom.xml

Use newest folio-system-user version with RTR fix
[FOLSPRINGB-132](https://issues.folio.org/browse/FOLSPRINGB-132)
[MSEARCH-550](https://issues.folio.org/browse/MSEARCH-550)

fix(deps): Upgrade to folio-spring-support v7.3.0-SNAPSHOT

---

NEWS.md
src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java
src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java

Fix number of titles counts in subjects and contributors browse when "No" is checked in "Shared" facet in consortium env.
Apply filter to the subresources to count only instances that are not shared and related to current tenant only.
https://issues.folio.org/browse/MSEARCH-639

fix(consortium): fix shared filter for subjects/contributors

---

src/main/java/org/folio/search/repository/InstanceSubjectRepository.java
src/test/java/org/folio/search/repository/InstanceSubjectRepositoryTest.java

Do not index "null" instanceId to subjects index
Skip payloads with "null" instanceId
[MSEARCH-642](https://issues.folio.org/browse/MSEARCH-642)

fix(subjects-indexing): Do not index "null" instanceId to subjects index

---

NEWS.md
pom.xml
src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java
src/main/java/org/folio/search/integration/KafkaMessageProducer.java
src/main/java/org/folio/search/service/browse/ContributorBrowseService.java
src/main/java/org/folio/search/service/browse/SubjectBrowseService.java
src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java
src/test/java/org/folio/search/integration/KafkaMessageProducerTest.java
src/test/java/org/folio/search/utils/TestUtils.java

Release v3.0.5
[MSEARCH-646](https://issues.folio.org/browse/MSEARCH-646)

Tmp release v3.0.5

---

NEWS.md
pom.xml

Bump module versions after release
- `3.1.0-SNAPSHOT` -> `3.2.0-SNAPSHOT`
[MSEARCH-664](https://issues.folio.org/browse/MSEARCH-664)

MSEARCH-664: bump module version after v3.1.0 was released

---

NEWS.md
src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java
src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java
src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java
src/test/java/org/folio/search/utils/TestUtils.java

Ignore call number format validation
Remove call number format validation for shelving order generation
[MSEARCH-689](https://folio-org.atlassian.net/browse/MSEARCH-689)

feat(cn-browse): Ignore call number format validation

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/search/controller/SearchConsortiumController.java
src/main/java/org/folio/search/model/service/ConsortiumSearchContext.java
src/main/java/org/folio/search/model/types/ResourceType.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceRepository.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceService.java
src/main/java/org/folio/search/service/consortium/ConsortiumSearchQueryBuilder.java
src/main/resources/swagger.api/mod-search.yaml
src/main/resources/swagger.api/schemas/item.json
src/test/java/org/folio/search/controller/SearchItemsConsortiumIT.java
src/test/java/org/folio/search/service/consortium/ConsortiumSearchQueryBuilderTest.java
src/test/java/org/folio/search/support/base/ApiEndpoints.java
src/test/resources/samples/instance-response-sample/instance-basic-response.json
src/test/resources/samples/instance-response-sample/instance-full-response.json
src/test/resources/samples/semantic-web-primer/items.json

implement endpoint for consolidate items access in consortium
- Define new API endpoint
- Implement logic for item fetching
https://folio-org.atlassian.net/browse/MSEARCH-693

feat(search-instances): implement endpoint for consolidate items access in consortium

---

src/main/java/org/folio/search/model/service/ConsortiumSearchContext.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceRepository.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceService.java
src/main/java/org/folio/search/service/consortium/ConsortiumSearchQueryBuilder.java
src/main/resources/swagger.api/mod-search.yaml
src/test/java/org/folio/search/controller/ConsortiumSearchHoldingsIT.java
src/test/java/org/folio/search/controller/ConsortiumSearchItemsIT.java
src/test/java/org/folio/search/service/consortium/ConsortiumSearchQueryBuilderTest.java

fix calculating totalNumber in response
Add additional query to fetch count
Add callNumberSuffix to response
https://folio-org.atlassian.net/browse/MSEARCH-710

fix(search-instances): fix calculating totalNumber in response

---

NEWS.md
pom.xml
src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java
src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java
src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java

Release v3.0.8, prepare v3.0.9-SNAPSHOT

Prepare new development iteration Poppy

---

NEWS.md
pom.xml
src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java
src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java
src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java

Release v3.2.1, set new dev version as v3.2.2

Prepare next development iteration Orchid

---

NEWS.md
pom.xml
src/main/java/org/folio/search/model/service/ConsortiumSearchContext.java
src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceRepository.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceService.java
src/main/java/org/folio/search/service/consortium/ConsortiumSearchQueryBuilder.java
src/main/resources/swagger.api/mod-search.yaml
src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java
src/test/java/org/folio/search/controller/ConsortiumSearchHoldingsIT.java
src/test/java/org/folio/search/controller/ConsortiumSearchItemsIT.java
src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java
src/test/java/org/folio/search/service/consortium/ConsortiumSearchQueryBuilderTest.java

Release v3.2.1, prepare v3.2.2-SNAPSHOT

Prepare next development iteration Quesnelia

---

descriptors/ModuleDescriptor-template.json

Add locations permission to tenant endpoint
[MSEARCH-702](https://folio-org.atlassian.net/browse/MSEARCH-702)

fix(search-locations): Add locations permission to tenant endpoint

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/search/controller/FacetsController.java
src/main/resources/application.yml
src/main/resources/swagger.api/parameters/record-type.yaml
src/main/resources/swagger.api/schemas/entity/recordType.yaml
src/test/java/org/folio/search/controller/BrowseClassificationConsortiumIT.java
src/test/java/org/folio/search/controller/FacetsControllerTest.java

Add support for instance classification facets
- update API definition for supported records types in facets
- update API to model conversion
- enable classification browse feature by default
https://folio-org.atlassian.net/browse/MSEARCH-727

feat(facets): add support for instance classification facets

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
.github/workflows/spectral-lint.yml

Fix api-doc workflow and replace api-lint with spectral lint

build: fix api-doc workflow and replace api-lint with spectral lint

---

src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java
src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java

Fix title count for subjects/contributors when on central tenant
- Count only shared instances for subject/contributor when on central tenant
[MSEARCH-745](https://folio-org.atlassian.net/browse/MSEARCH-745)

fix(browse-contributors-subjects): Fix title count when on central tenant

---

NEWS.md
pom.xml
src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java
src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java

Relsease v3.2.4 and prepare for 3.2.5 development iteration
[MSEARCH-739](https://folio-org.atlassian.net/browse/MSEARCH-739)

Prepare for 3.2.5 development iteration

---

NEWS.md
src/main/java/org/folio/search/model/dto/LocationDto.java
src/main/resources/model/location.json
src/main/resources/swagger.api/schemas/entity/consortiumLocation.yaml
src/test/java/org/folio/search/controller/ConsortiumSearchLocationsIT.java
src/test/java/org/folio/search/controller/LocationsIndexingConsortiumIT.java
src/test/java/org/folio/search/service/consortium/ConsortiumLocationServiceTest.java

_Extend response with additional Location fields for Inventory Locations in a Consortium endpoint_
_Update ConsortiumLocation and LocationDto schemas_
_List any Jira issues related to this pull request._
[MSEARCH-775](https://folio-org.atlassian.net/browse/MSEARCH-775)

MSEARCH-775: Extend Inventory Locations in Consortia endpoint with additional response fields

---

src/main/java/org/folio/search/controller/SearchConsortiumController.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceSearchService.java
src/test/java/org/folio/search/service/consortium/ConsortiumInstanceSearchServiceTest.java

_Fix totalRecords calculation_
_calculate over all search results' total records count_
[MSEARCH-785](https://folio-org.atlassian.net/browse/MSEARCH-785)

MSEARCH-785: Fix totalRecords calculation for consortium holding/items endpoints

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/search/client/LocationsClient.java
src/main/resources/model/institution.json
src/test/java/org/folio/search/controller/IndexManagementIT.java
src/test/java/org/folio/search/service/IndexServiceTest.java
src/test/java/org/folio/search/service/LocationServiceTest.java
src/test/resources/mappings/inventory-institutions.json

Implement Reindexing of Libraries [[MSEARCH-768]](<https://folio-org.atlassian.net/browse/MSEARCH-768>)
- Add mod-inventory-storage institutions client
- Update institutions model to support institutions reindex
- Update reindex service to support institutions reindex
- Implement institutions reindexing by repeatedly querying institutions from mod-inventory-storage and indexing them
- Verified by testing manually, added commend to JIRA ticket: https://folio-org.atlassian.net/browse/MSEARCH-768?focusedCommentId=221391
Implement Reindexing of Locations ([MSEARCH-702](https://folio-org.atlassian.net/browse/MSEARCH-702))
Implement Reindexing of Libraries ([MSEARCH-766](https://folio-org.atlassian.net/browse/MSEARCH-766))
Implement Reindexing of Campuses …

[MSEARCH-768] Implement Reindexing of Institutions

---

NEWS.md
src/main/java/org/folio/search/configuration/KafkaConfiguration.java
src/main/java/org/folio/search/integration/KafkaMessageListener.java
src/main/java/org/folio/search/repository/InstanceContributorsRepository.java
src/main/java/org/folio/search/repository/InstanceSubjectRepository.java
src/main/java/org/folio/search/service/IndexService.java
src/main/java/org/folio/search/service/LanguageConfigService.java
src/main/java/org/folio/search/service/ResourceService.java
src/main/java/org/folio/search/service/consortium/ConsortiumInstanceService.java
src/main/java/org/folio/search/service/consortium/ConsortiumTenantExecutor.java
src/main/java/org/folio/search/service/consortium/LanguageConfigServiceDecorator.java
src/main/java/org/folio/search/service/converter/MultiTenantSearchDocumentConverter.java
src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java
src/main/java/org/folio/search/service/converter/preprocessor/InstanceEventPreProcessor.java
src/test/java/org/folio/search/controller/RecordsIndexingIT.java
src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java
src/test/java/org/folio/search/service/LanguageConfigServiceTest.java
src/test/java/org/folio/search/service/ResourceServiceTest.java
src/test/java/org/folio/search/service/consortium/LanguageConfigServiceDecoratorTest.java
src/test/java/org/folio/search/service/converter/MultiTenantSearchDocumentConverterTest.java
src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java

Reverts folio-org/mod-search#608

Revert "fix(indexing): retry on consumer don't define new context"

---

pom.xml
src/main/java/org/folio/search/service/converter/preprocessor/AuthorityEventPreProcessor.java
src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java
src/main/java/org/folio/search/service/metadata/ResourceDescriptionService.java

_Fix dependencies after Spring version upgrade_
- use jakarta import for ```@PostConstruct``` annotation
- remove dependency for [Awaitility](https://github.com/awaitility/awaitility), it's now part of spring-boot-starter-test
[MSEARCH-810](https://folio-org.atlassian.net/browse/MSEARCH-810)
https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#core-container-1
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#miscellaneous

MSEARCH-810: Fix dependencies after Spring version upgrade

---

src/main/java/org/folio/search/service/consortium/ConsortiumLocationService.java
src/main/resources/swagger.api/parameters/consortium-locations-limit-param.yaml
src/test/java/org/folio/search/service/consortium/ConsortiumLocationServiceTest.java

In scope of ticket we need to fetch all available locations to check by code https://github.com/folio-org/mod-gobi/pull/238
Increasing max limit for api search/consortium/locations
https://folio-org.atlassian.net/browse/MSEARCH-812

[MSEARCH-812] Increase the limit to fetch more than 1k locations

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/search/controller/IndexManagementController.java
src/main/java/org/folio/search/converter/ReindexStatusMapper.java
src/main/java/org/folio/search/model/reindex/ReindexStatusEntity.java
src/main/java/org/folio/search/model/types/ReindexStatus.java
src/main/java/org/folio/search/service/reindex/ReindexOrchestrationService.java
src/main/java/org/folio/search/service/reindex/ReindexRangeIndexService.java
src/main/java/org/folio/search/service/reindex/jdbc/ReindexStatusRepository.java
src/main/resources/changelog/changes/v4.0/create-reindex-entity-tables.xml
src/main/resources/changelog/changes/v4.0/update-reindex-status-trigger.sql
src/main/resources/swagger.api/examples/result/ReindexStatusResult.yaml
src/main/resources/swagger.api/mod-search.yaml
src/main/resources/swagger.api/parameters/reindex-id-param.yaml
src/main/resources/swagger.api/paths/search-index/search-index-reindex-status.yaml
src/main/resources/swagger.api/schemas/response/reindexStatusItem.yaml
src/test/java/org/folio/search/controller/IndexManagementControllerTest.java
src/test/java/org/folio/search/service/reindex/ReindexOrchestrationServiceTest.java
src/test/java/org/folio/search/service/reindex/ReindexRangeIndexServiceTest.java
src/test/java/org/folio/search/service/reindex/jdbc/ReindexStatusRepositoryIT.java
src/test/java/org/folio/search/support/base/ApiEndpoints.java
src/test/resources/sql/populate-reindex-status.sql

Implement Reindex status Endpoint
- Implement DB schema
- Implement status update trigger on processed items updates
- Implement endpoint
[MSEARCH-797](https://folio-org.atlassian.net/browse/MSEARCH-797)

feat(reindex): Implement Reindex status Endpoint

---

README.md

Fix reindex resource name
_List any Jira issues related to this pull request._
[MSEARCH-818](https://folio-org.atlassian.net/browse/MSEARCH-818)

docs(re-index): Fix resource name

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/resources/application.yml

_Add documentation for improved instances reindex_
_Update README.md, ModuleDescriptor and related files_
[MSEARCH-842](https://folio-org.atlassian.net/browse/MSEARCH-842)

MSEARCH-842: Add documentation for improved Instance and related resources reindexing

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Bump the required instance-storage interface to v11.0
https://folio-org.atlassian.net/browse/MSEARCH-843

build: bump the required instance-storage interface to v11.0

---

.github/workflows/api-doc.yml

_Fix list of APIs file generation_
_modify api-doc.yml_
[MSEARCH-840](https://folio-org.atlassian.net/browse/MSEARCH-840)

MSEARCH-840: Fix dead link in config-doc.json

---

src/main/resources/swagger.api/parameters/instance-subjects-browse-cql-query.yaml

[MSEARCH-805](https://folio-org.atlassian.net/browse/MSEARCH-805)

docs(browse-contributors-subjects): Add new subject filter options

---

descriptors/ModuleDescriptor-template.json

Remove inventory-view dependency as it's not used anymore.

Remove inventory-view dependency

---

NEWS.md
pom.xml
src/test/java/org/folio/search/controller/SearchInstanceConsortiumIT.java
src/test/java/org/folio/search/controller/SearchInstanceIT.java

prepare for next development iteration v4.1.0

chore: prepare for next development iteration v4.1.0

---

NEWS.md
src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java
src/main/resources/elasticsearch/index/authority.json
src/main/resources/elasticsearch/index/linked-data-hub.json
src/main/resources/elasticsearch/index/linked-data-instance.json
src/main/resources/elasticsearch/index/linked-data-work.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/resources/samples/instance-response-sample/instance-full-response.json
src/test/resources/samples/semantic-web-primer/instance.json

Fix wildcard search for diacritics
- Use keyword_icu instead of keyword_lowercase for fulltext fields plain values
[MSEARCH-857](https://folio-org.atlassian.net/browse/MSEARCH-857)

fix(search-instances): Fix wildcard search for diacritics

---

NEWS.md
pom.xml
src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java
src/main/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessor.java
src/main/resources/elasticsearch/index/authority.json
src/main/resources/elasticsearch/index/linked-data-hub.json
src/main/resources/elasticsearch/index/linked-data-instance.json
src/main/resources/elasticsearch/index/linked-data-work.json
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessorTest.java
src/test/resources/samples/instance-response-sample/instance-full-response.json
src/test/resources/samples/semantic-web-primer/instance.json

Release v4.0.1 and prepare v4.0.2-SNAPSHOT development iteration

Prepare v4.0.2-SNAPSHOT development iteration

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/search/integration/message/KafkaMessageListener.java
src/main/java/org/folio/search/integration/message/interceptor/ResourceEventBatchInterceptor.java
src/main/java/org/folio/search/model/types/ResourceType.java
src/main/java/org/folio/search/service/browse/ClassificationBrowseService.java
src/main/java/org/folio/search/service/config/BrowseConfigService.java
src/main/java/org/folio/search/service/config/ConfigSynchronizationService.java
src/main/java/org/folio/search/utils/KafkaConstants.java
src/main/java/org/folio/search/utils/ShelvingOrderCalculationHelper.java
src/main/resources/application.yml
src/main/resources/changelog/changelog-master.xml
src/main/resources/changelog/changes/v4.1/populate-call-number-browse-config.xml
src/main/resources/swagger.api/schemas/entity/browseOptionType.yaml
src/main/resources/swagger.api/schemas/entity/browseType.yaml
src/main/resources/swagger.api/schemas/entity/shelvingOrderAlgorithmType.yaml
src/test/java/org/folio/search/controller/BrowseClassificationIT.java
src/test/java/org/folio/search/controller/ConfigControllerTest.java
src/test/java/org/folio/search/controller/ConfigIT.java
src/test/java/org/folio/search/integration/KafkaMessageListenerTest.java
src/test/java/org/folio/search/service/config/BrowseConfigServiceTest.java
src/test/java/org/folio/search/service/config/ConfigSynchronizationServiceTest.java
src/test/java/org/folio/search/service/consortium/BrowseConfigServiceDecoratorTest.java
src/test/java/org/folio/search/utils/ShelvingOrderCalculationHelperTest.java
src/test/java/org/folio/search/utils/TestConstants.java
src/test/java/org/folio/search/utils/TestUtils.java
src/test/resources/application.yml

Implement call number browse config
- Populate default call number browse configs in db
- Update browse config endpoints
- Implement call number type events consumer
[MSEARCH-863](https://folio-org.atlassian.net/browse/MSEARCH-863)

feat(cn-browse): Implement call number browse config

---

NEWS.md
src/main/java/org/folio/search/configuration/SearchCacheNames.java
src/main/java/org/folio/search/service/config/BrowseConfigService.java
src/main/resources/application.yml
src/test/resources/application.yml

Fix issue with old browse config being used
Remove browse config caching
[MSEARCH-897](https://folio-org.atlassian.net/browse/MSEARCH-897)

fix(browse): Fix issue with old browse config being used

---

NEWS.md
pom.xml
src/main/java/org/folio/search/configuration/SearchCacheNames.java
src/main/java/org/folio/search/service/config/BrowseConfigService.java
src/main/resources/application.yml
src/test/resources/application.yml

Release v4.0.3, prepare v4.0.4 development iteration
[MSEARCH-917](https://folio-org.atlassian.net/browse/MSEARCH-917)
[MSEARCH-897](https://folio-org.atlassian.net/browse/MSEARCH-897)

Release v4.0.3, prepare v4.0.4 development iteration

---

NEWS.md
src/main/java/org/folio/search/service/reindex/ReindexOrchestrationService.java
src/main/java/org/folio/search/service/reindex/ReindexStatusService.java
src/test/java/org/folio/search/service/reindex/ReindexOrchestrationServiceTest.java
src/test/java/org/folio/search/service/reindex/ReindexStatusServiceTest.java

Update reindex status logic for failures
Update reindex merge failed status only for failed entity type
[MSEARCH-909](https://folio-org.atlassian.net/browse/MSEARCH-909)

feat(reindex): Update reindex status logic for failures

---

NEWS.md
src/main/java/org/folio/search/model/reindex/MergeRangeEntity.java
src/main/java/org/folio/search/model/reindex/UploadRangeEntity.java
src/main/java/org/folio/search/model/types/ReindexRangeStatus.java
src/main/java/org/folio/search/service/reindex/ReindexMergeRangeIndexService.java
src/main/java/org/folio/search/service/reindex/ReindexOrchestrationService.java
src/main/java/org/folio/search/service/reindex/ReindexUploadRangeIndexService.java
src/main/java/org/folio/search/service/reindex/jdbc/MergeRangeRepository.java
src/main/java/org/folio/search/service/reindex/jdbc/ReindexJdbcRepository.java
src/main/java/org/folio/search/service/reindex/jdbc/UploadRangeRepository.java
src/main/resources/changelog/changelog-master.xml
src/main/resources/changelog/changes/v4.0/add-reindex-range-statuses.xml
src/test/java/org/folio/search/integration/folio/InventoryServiceTest.java
src/test/java/org/folio/search/service/reindex/ReindexMergeRangeIndexServiceTest.java
src/test/java/org/folio/search/service/reindex/ReindexOrchestrationServiceTest.java
src/test/java/org/folio/search/service/reindex/ReindexServiceTest.java
src/test/java/org/folio/search/service/reindex/jdbc/MergeRangeRepositoriesIT.java
src/test/java/org/folio/search/service/reindex/jdbc/ReindexJdbcRepositoriesIT.java
src/test/java/org/folio/search/service/reindex/jdbc/UploadRangeRepositoriesIT.java
src/test/resources/sql/populate-instances.sql

Extend range tables with the status, fail_cause columns
- add status, failCause columns to merge/upload range tables
- implement status population logic
[MSEARCH-870](https://folio-org.atlassian.net/browse/MSEARCH-870)

feat(reindex): Extend range tables with the status column

---

NEWS.md
pom.xml

[MSEARCH-918](https://folio-org.atlassian.net/browse/MSEARCH-918)

Prepare for 4.0.5 development iteration

---

NEWS.md
pom.xml
src/test/java/org/folio/search/controller/IndexManagementControllerTest.java
src/test/java/org/folio/search/service/reindex/jdbc/MergeRangeRepositoriesIT.java
src/test/java/org/folio/search/service/reindex/jdbc/ReindexStatusRepositoryIT.java
src/test/java/org/folio/search/service/reindex/jdbc/UploadRangeRepositoriesIT.java

Release v4.0.7, prepare v4.0.8 development iteration
[MSEARCH-938](https://folio-org.atlassian.net/browse/MSEARCH-938)

Prepare v4.0.8 development iteration

---

.github/workflows/api-doc.yml
NEWS.md
src/main/resources/swagger.api/mod-search.yaml

Fix documentation not being updated
Fix generated filename
[MSEARCH-937](https://folio-org.atlassian.net/browse/MSEARCH-937)
Documentation was properly generated/updated and uploaded to s3, but link on dev.folio.org was pointing to the old file being mod-search.html while new documentation was generated as openapi.html.

docs(api-docs): Fix documentation not being updated

---

src/main/java/org/folio/search/utils/CallNumberUtils.java
src/test/java/org/folio/search/controller/SearchInstanceIT.java
src/test/java/org/folio/search/service/reindex/jdbc/CallNumberRepositoryIT.java
src/test/java/org/folio/search/utils/CallNumberUtilsTest.java
src/test/resources/samples/instance-response-sample/instance-basic-response.json
src/test/resources/samples/instance-response-sample/instance-full-response.json

Update order of call number components in fullCallNumber
https://folio-org.atlassian.net/browse/MSEARCH-949

feat(cn-browse): update order of call number components in fullCallNumber

---

.github/workflows/api-doc.yml
NEWS.md

Fix "Fix dead link" workflow step for release builds
Fix file path
[MSEARCH-947](https://folio-org.atlassian.net/browse/MSEARCH-947)

docs(api-docs): Fix "Fix dead link" workflow step for release builds

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/test/resources/mappings/users.json

Add users.item.put to tenant endpoint module permissions
[MSEARCH-952](https://folio-org.atlassian.net/browse/MSEARCH-952)

chore(permissions): Add users.item.put to tenant endpoint module permissions

---

.github/workflows/api-doc.yml
NEWS.md
pom.xml

Release v4.0.9
[MSEARCH-971](https://folio-org.atlassian.net/browse/MSEARCH-971)

Tmp release v4.0.9

---

NEWS.md
README.md

Add missing documentation for specifying Elasticsearch/Opensearch index settings
update README 
[MSEARCH-789](https://folio-org.atlassian.net/browse/MSEARCH-789)

MSEARCH-789: Add documentation for specifying elasticsearch index settings

---

NEWS.md
src/main/java/org/folio/search/service/browse/AbstractShelvingOrderBrowseServiceBySearchAfter.java
src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java
src/main/java/org/folio/search/service/browse/ClassificationBrowseService.java
src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java

fix incorrect count for same call-number in one instance 
[MSEARCH-992](https://folio-org.atlassian.net/browse/MSEARCH-992)

fix(cn-browse): fix incorrect count for same call-number in one instance

---

NEWS.md
src/main/java/org/folio/search/service/config/BrowseConfigService.java
src/test/java/org/folio/search/service/config/BrowseConfigServiceTest.java

Fix exception while trying to validate empty type ids in browse-config
Add if check
https://folio-org.atlassian.net/browse/MSEARCH-998

fix(browse-config): exception while trying to validate empty type ids

---

NEWS.md
src/main/java/org/folio/search/service/reindex/ReindexService.java
src/test/java/org/folio/search/service/reindex/ReindexServiceTest.java

Fix records being indexed before index is recreated
Move index recreation before merge range publishing
[MSEARCH-1006](https://folio-org.atlassian.net/browse/MSEARCH-1006)

fix(reindex): Fix records being indexed before index is recreated

---

NEWS.md
src/main/java/org/folio/search/model/metadata/ResourceDescription.java
src/main/java/org/folio/search/service/es/SearchMappingsHelper.java
src/main/resources/model/authority.json
src/main/resources/model/instance.json
src/test/java/org/folio/search/service/es/SearchMappingsHelperTest.java

Keep all sources in indexes
Remove mappingsSource configuration
https://folio-org.atlassian.net/browse/MSEARCH-1031

feat(index-management): remove mappingsSource configuration

---

NEWS.md
pom.xml

Release v4.0.13 prepare v4.0.14-SNAPSHOT development iteration
[MSEARCH-1034](https://folio-org.atlassian.net/browse/MSEARCH-1034)

Release v4.0.13 prepare v4.0.14-SNAPSHOT development iteration

---

NEWS.md
src/main/java/org/folio/search/service/reindex/jdbc/MergeRangeRepository.java
src/main/java/org/folio/search/utils/JdbcUtils.java
src/test/java/org/folio/search/service/reindex/jdbc/MergeRangeRepositoriesIT.java

Fix issue while handling delete item events 
Mofidy SQL query
https://folio-org.atlassian.net/browse/MSEARCH-1064

fix(indexing): proper handling of delete item events

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Add missing interface dependencies in module descriptor
https://folio-org.atlassian.net/browse/MSEARCH-1062

build: add missing interface dependencies in module descriptor

---

NEWS.md
src/main/resources/application.yml
src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java
src/test/resources/application.yml

Use unique consumer group per instance for inventory classification-type and call-number-type topics
https://folio-org.atlassian.net/browse/MSEARCH-1092

feat: use unique consumer group per instance for inventory classification-type and call-number-type topics
