folio-org/mod-search

descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
https://issues.folio.org/browse/MSEARCH-38 - Update module-descriptor with new APIs
* Update module descriptor and add new APIs:
* `indexes` contains all operations for indexes (create/update index, index resources)
*  `search` contains instance search API;
* Assign permissions for each endpoint;
* Requires `instance-storage:7.5` API (it is not directly queried but needed to prevent breaking changes being applied to the instance schema without the team notification).
* Inject kafka host and port and elasticsearch host and port from env variables.
=> MSEARCH-38: Update module descriptor.

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/SearchController.java, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/model/service/CqlSearchRequest.java, src/main/resources/model/instance.json, src/main/resources/swagger.api/mod-search.yaml, src/test/java/org/folio/search/controller/EsInstanceToInventoryInstanceIT.java, src/test/java/org/folio/search/controller/SearchControllerTest.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/repository/SearchRepositoryTest.java, src/test/java/org/folio/search/service/SearchServiceTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java
https://issues.folio.org/browse/MSEARCH-46 - Allow returning of all instance properties.
* Add new `expandAll` property for the `/search/instances` endpoint;
* Bump up minor version for the API;
* Add tests for the new change.
* Make `identifierTypeId` as source.
=> MSEARCH-46: Add expandAll property for /search/instances

descriptors/ModuleDescriptor-template.json
Reverts folio-org/mod-search#24
=> Revert "FOLIO-2997 Set port for elasticsearch in default LaunchDescriptor"

src/main/resources/application.yml
There is a known restrictions related to URI length for GET requests, it is limited to ~1000 bytes.
This PR makes the batch size for consumer = 50 so that there will be no case when we rich this URI limit (50 ids is sent in inventory-view request)
=> MSEARCH-75: Make Kafka consumer batch smaller.

src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/holding.json, src/main/resources/swagger.api/schemas/item.json, src/test/java/org/folio/search/controller/EsInstanceToInventoryInstanceIT.java, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java
- [MSEARCH-55](https://issues.folio.org/browse/MSEARCH-55) Instance - filter/facet by item effective locations 
- [MSEARCH-56](https://issues.folio.org/browse/MSEARCH-56) Holdings - filter/facet by permanent locations 
- [MSEARCH-63](https://issues.folio.org/browse/MSEARCH-63) Item - status filters/facets
=> MSEARCH-55 Implement filters and facets for item and holding fields

src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java, src/main/java/org/folio/search/service/setter/item/EffectiveCallNumberComponentsProcessor.java, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/item.json, src/test/java/org/folio/search/controller/SearchItemIT.java, src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java, src/test/java/org/folio/search/service/setter/item/EffectiveCallNumberComponentsProcessorTest.java, src/test/resources/samples/semantic-web-primer/items.json
1. Generate a synthetic instance-level property called `itemsFullCallNumbers` - that is a string array of concatenated `prefix callNumber suffix` (concatenated with space) for each item of the instance. The property has search aliases -  `items.effectiveCallNumberComponents`, `items.fullCallNumber`.
2. The `src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java` has been updated to support the search aliases for `searchFields` as well as for regular fields.
=> MSEARCH-12: Implement items.effectiveCallNumberComponents search.

src/main/java/org/folio/search/controller/FolioTenantController.java, src/main/java/org/folio/search/exception/TenantNotInitializedException.java, src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/integration/error/KafkaErrorHandler.java, src/main/java/org/folio/search/service/systemuser/SystemUserService.java, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/java/org/folio/search/integration/error/KafkaErrorHandlerTest.java
When kafka listener starts consuming events from the topic but tenant is not initialized yet we throw a `TenantNotInitializedException` vs a sql exception which confuses folks.
=> MSEARCH-72: Throw more explicit error if tenant is not initialized yet

.gitignore, src/main/java/org/folio/search/service/systemuser/SystemUserService.java, src/main/resources/application.yml, src/test/java/org/folio/search/service/systemuser/SystemUserServiceTest.java, src/test/resources/application.yml
This PR is to address below error in Bugfest env when enabling mod-search for tenant. See https://issues.folio.org/browse/MSEARCH-85
`Caused by: java.io.FileNotFoundException: class path resource [permissions/mod-search.csv] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/usr/ms/ms.jar!/BOOT-INF/classes!/permissions/mod-search.csv`
=> MSEARCH-85 cannot read mod-search.csv from classpath

NEWS.md, pom.xml, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/repository/IndexRepository.java, src/main/java/org/folio/search/service/IndexService.java, src/main/java/org/folio/search/service/converter/MultiTenantSearchDocumentConverter.java, src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java, src/main/java/org/folio/search/utils/SearchConverterUtils.java, src/main/resources/swagger.api/schemas/resourceEventBody.json, src/test/java/org/folio/search/controller/IndexingIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/service/IndexServiceTest.java, src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java, src/test/java/org/folio/search/support/api/InventoryApi.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
Includes: 
* https://github.com/folio-org/mod-search/pull/60 - MSEARCH-86 Implement caching of existing indices
* https://github.com/folio-org/mod-search/pull/64 - MSEARCH-90: Support delete events.
* https://github.com/folio-org/mod-search/pull/63 - MSEARCH-91 Use operator 'AND' for match queries [PT1]
=> Release mod-search 1.2.1

src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/service/IndexService.java, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/java/org/folio/search/integration/KafkaMessageListenerTest.java, src/test/java/org/folio/search/service/IndexServiceTest.java
When Indexing resources make sure ES index exists before starting any logic: converting resources, calling inventory, etc.
=> MSEARCH-112: Check that ES index exists before any indexing logic.

src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/electronicAccess.json, src/main/resources/swagger.api/schemas/holding.json, src/main/resources/swagger.api/schemas/instance.json, src/main/resources/swagger.api/schemas/item.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/resources/samples/semantic-web-primer/holdings.json, src/test/resources/samples/semantic-web-primer/instance.json, src/test/resources/samples/semantic-web-primer/items.json
Following stories are similar and done in single PR:
- [MSEARCH-109](https://issues.folio.org/browse/MSEARCH-109) Implement search by items electronic access
- [MSEARCH-110](https://issues.folio.org/browse/MSEARCH-110) Implement search by holdings electronic access
=> MSEARCH-109 Implement search by items/holdings electronic access

src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java, src/main/resources/elasticsearch/index/instance.json, src/test/java/org/folio/search/controller/ConfigControllerIT.java, src/test/java/org/folio/search/controller/EsInstanceToInventoryInstanceIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/java/org/folio/search/utils/TestUtils.java, src/test/resources/samples/semantic-web-primer/instance.json
* Add ASCII folding filter for multilang fields (src property);
* `Src` field is always present for multilang now.
=> MSEARCH-67: Add ASCII folding filter.

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/ApiExceptionHandler.java, src/main/java/org/folio/search/controller/ConfigController.java, src/main/java/org/folio/search/converter/LanguageConfigConverter.java, src/main/java/org/folio/search/model/config/LanguageConfigEntity.java, src/main/java/org/folio/search/model/types/ErrorCode.java, src/main/java/org/folio/search/service/LanguageConfigService.java, src/main/java/org/folio/search/service/es/SearchMappingsHelper.java, src/main/resources/changelog/changes/initial_schema.xml, src/main/resources/elasticsearch/index-field-types.json, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/languageConfig.json, src/test/java/org/folio/search/controller/ConfigControllerIT.java, src/test/java/org/folio/search/controller/ConfigControllerTest.java, src/test/java/org/folio/search/service/LanguageConfigServiceTest.java, src/test/java/org/folio/search/service/es/SearchMappingsHelperTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/java/org/folio/search/utils/TestUtils.java
- Environment specific analyzer can be passed as part of language config entity
- Default analyzer for Korean language set to seunjeon_analyzer
=> MSEARCH-89 Add ability to specify language analyzer in configuration

src/main/resources/elasticsearch/index/instance.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/resources/samples/semantic-web-primer/instance.json
Replace `asciifolding` filter with `icu_folding` filter as it also able to process accents for unicode characters.
* [ICU Folding Token Filter](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-folding.html)
* [ASCII Folding Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/7.12/analysis-asciifolding-tokenfilter.html)
=> MSEARCH-67: Replace asciifolding filter with icu_folding filter.

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/IndexController.java, src/main/java/org/folio/search/repository/IndexRepository.java, src/main/java/org/folio/search/service/IndexService.java, src/main/resources/swagger.api/examples/reindexRequest.sample, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/request/reindexRequest.json, src/test/java/org/folio/search/controller/IndexControllerTest.java, src/test/java/org/folio/search/service/IndexServiceTest.java
Reindex endpoint `.../search/index/inventory/reindex` has been extended with bool query parameter `recreateIndex`, if it specified and equals to true - indices for tenant will be recreated. This parameter reduces the amount of API calls to the mod-search service to clean up indices and start reindex:
- `DELETE {elasticsearchBaseUrl}/instance_{tenantID}` to remove elasticsearch index
- `POST {modSearchBaseUrl}/search/index/indices -d '{"resourceName": "instance"}'` to create new index again with new mappings and settings
=> MSEARCH-121 Add ability to recreate index before starting reindex

README.md, src/main/java/org/folio/search/configuration/properties/FolioEnvironment.java, src/main/resources/application.yml, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/resources/application.yml
Introduce `ENV` variable to differentiate environments and build consumer group id appending the env name.
=> MSEARCH-129: Make consumer name different per environment.

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
There were some concerns raised in the community regarding how secure the direct connection will be. To address these concerns, the new solution was designed: https://wiki.folio.org/display/DD/Temporary+Kafka+security+solution.
The solution was reviewed and approved by the Security group and Tech Council.
Add the following environment variables to the application to handle Spring Boot properties:
- KAFKA_SECURITY_PROTOCOL (`spring.kafka.security.protocol`)
- KAFKA_SSL_KEYSTORE_PASSWORD (`spring.kafka.ssl.key-store-password`)
- KAFKA_SSL_KEYSTORE_LOCATION (`spring.kafka.ssl.key-store-location`)
- KAFKA_SSL_TRUSTSTORE_PASSWORD (`spring.kafka.ssl.trust-store-password`)
- KAFKA_SSL_TRUSTSTORE_LOCATION (`spring.kafka.ssl.trust-store-location`)
=> MSEARCH-105 Add TLS settings as environment variables for Kafka consumer

README.md, src/main/java/org/folio/search/configuration/properties/FolioEnvironment.java, src/main/java/org/folio/search/configuration/properties/OkapiConfigurationProperties.java, src/main/java/org/folio/search/service/systemuser/SystemUserService.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/test/java/org/folio/search/configuration/properties/FolioEnvironmentTest.java, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/java/org/folio/search/repository/IndexRepositoryTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java, src/test/java/org/folio/search/utils/TestConstants.java, src/test/java/org/folio/search/utils/TestUtils.java
The `ENV` variable is used as a prefix for ES index, `ENV` value is restricted to contain alphanumeric and '_', '-' symbols only.
=> MSEARCH-95: Use ENV name as prefix for Elasticsearch index.

src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java, src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java, src/main/java/org/folio/search/service/converter/SearchFieldsProcessor.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java, src/test/java/org/folio/search/utils/TestUtils.java
While searching contributors =="carols" the search returns records with contributors Carole and Carol
* in searches for `contributors == "<name>s"` is not treated as a plural form but as part of the name
The main change is adding support for fields with index = `standard` as full-text fields. They will be recognized by the CQL query converter and the same rules as for the multilanguage fields will be applied.
Integration and unit tests are added to prove of added functionality
=> MSEARCH-134 Remove multi-language support from the contributors fields

src/main/java/org/folio/search/service/setter/instance/SortTitleProcessor.java, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/SortInstanceIT.java, src/test/java/org/folio/search/service/setter/instance/SortTitleProcessorTest.java
The current implementation sorts by `instance.title` property but the preferred behavior is to sort by `instance.indexTitle`
The sorting by title should behave as follows:
- if `instance.indexTitle` is populated, it is used for sorting
- if `instance.indexTitle` is not populated, sort by `instance.title` field
Implement new `SortTitleProcessor` which will chose one of titles - `indexTitle` or `title`. If `indexTitle` is blank, `title` will be analyzed and if it is not empty - it will be used for sorting. If `indexTitle` is not blank - it will be used for sorting.
Integration and unit tests are added to prove developed functionality.
=> MSEARCH-136 Adjust sorting by title to use indexTitle if possible

src/main/java/org/folio/search/configuration/KafkaConfiguration.java, src/main/java/org/folio/search/configuration/properties/FolioKafkaProperties.java, src/main/java/org/folio/search/controller/FolioTenantController.java, src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/service/KafkaAdminService.java, src/main/resources/application.yml, src/test/java/org/folio/search/configuration/FolioKafkaPropertiesTest.java, src/test/java/org/folio/search/controller/FolioTenantControllerTest.java, src/test/java/org/folio/search/service/KafkaAdminServiceTest.java, src/test/java/org/folio/search/support/api/InventoryApi.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/java/org/folio/search/utils/TestConstants.java, src/test/resources/application.yml
Many modules that use Kafka use ENV variable and tenant id in their naming convention for topics.
For example topics in Bugfest have names that include ENV (ibf3) in addition to tenant id (fs09000000) - such as the following topic example
`ibf3.Default.fs09000000.DI_COMPLETED`
It would be helpful if ENV and tenant id settings were used in the topic naming convention. This would allow a Kafka instance to be shared by multiple environments that have the same tenant id.
https://github.com/folio-org/mod-search/blob/master/src/main/resources/kafka/kafka-topics.json
Required topic pattern - `{env}.{tenant}.{topicname}`
A new approach listens to the topics patterns instead of a list of provided topics. This will allow to mod-search receive messages from topics starting from the `ENV` variable …
=> MSEARCH-132 Apply new topic naming convention

src/main/java/org/folio/search/service/setter/holding/HoldingPublicNotesProcessor.java, src/main/java/org/folio/search/service/setter/holding/HoldingTagsProcessor.java, src/main/java/org/folio/search/service/setter/holding/HoldingsCallNumberComponentsProcessor.java, src/main/java/org/folio/search/service/setter/instance/AbstractIdentifierProcessor.java, src/main/java/org/folio/search/service/setter/instance/AbstractPublicNotesProcessor.java, src/main/java/org/folio/search/service/setter/instance/PublicNotesProcessor.java, src/main/java/org/folio/search/service/setter/item/EffectiveCallNumberComponentsProcessor.java, src/main/java/org/folio/search/service/setter/item/ItemPublicNotesProcessor.java, src/main/java/org/folio/search/service/setter/item/ItemTagsProcessor.java, src/main/java/org/folio/search/utils/CollectionUtils.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/holding.json, src/main/resources/swagger.api/schemas/instance.json, src/main/resources/swagger.api/schemas/item.json, src/main/resources/swagger.api/schemas/note.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/setter/holding/HoldingPublicNotesProcessorTest.java, src/test/java/org/folio/search/service/setter/instance/PublicNotesProcessorTest.java, src/test/java/org/folio/search/service/setter/item/ItemPublicNotesProcessorTest.java, src/test/java/org/folio/search/utils/CollectionUtilsTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java, src/test/resources/application.yml, src/test/resources/samples/semantic-web-primer/holdings.json, src/test/resources/samples/semantic-web-primer/items.json
The purpose of this pull request is to allow the user a full-text search within the instance/item/holdings record's notes field. Search should support using public only and all `notes.note` values.
- Existing search by public notes of instance only is preserved
- Additional search option notes (all) is added
- Query returns accurate hit count
- User can search by any word that is a part of the field's value
- Results are ranked based on term frequency, inverse document frequency, and field length
- Stemming according to with configured on the tenant language tokenizers
Since the approach for implementing full-text search support for the following fields `notes.note`, `items.notes.note`, `holdings.notes.note` is similar, all 3 stories are merged into a single pull request.
Integration and …
=> MSEARCH-117 Support full text search for notes of linked holding-records

src/main/java/org/folio/search/utils/SearchUtils.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java
SearchUtils contains some methods from the cherry-picked commits, that are not used and prevents the build from passing quality gates
=> MSEARCH-117 Increase code coverage

src/main/resources/elasticsearch/index/instance.json, src/test/resources/application.yml
The current configuration has a value for the number of fields limitation as 250. With 5 assigned languages it raised an error for the previous version of mapping. 
- Change mapping.total_fields.limit property to 1000
- Add 5th language to the test configuration to cover the maximum number of fields
=> MSEARCH-160 Failed to create index: Limit of total fields [250] has been exceeded

README.md, src/main/resources/application.yml, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/resources/application.yml
The current subscription pattern allows mod-search to receive events from non-specified by envId topics. In the scope of this PR, an additional environment variable should be added to customize a subscription pattern for a particular environment.
- Change  topic-pattern in application.yml
- Add test to check this variable
=> MSEARCH-164 Fix reindex problem on juniper bugfest

README.md, src/main/java/org/folio/search/service/setter/holding/HoldingIdentifiersProcessor.java, src/main/java/org/folio/search/service/setter/item/ItemIdentifiersProcessor.java, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/holding.json, src/main/resources/swagger.api/schemas/item.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/resources/samples/semantic-web-primer/holdings.json, src/test/resources/samples/semantic-web-primer/items.json
The current implementation supports holdings search by HRID but librarians also need to search by holdings and items by their former Id.  While searching it is not always clear if the provided value is a current or a former HRID.  For those cases, there need to be an option to cover both in one search
- Add Identifiers (all) option for holdings and items
- The search should include matches from hrid and fromerIds (array of strings)
-Added new search fields: itemIdentifiers and holdingIdentifiers. These fields should support searching by hrId and former ids
=> MSEARCH-152/153 Add Identifiers (all) search option for holding and items

src/main/java/org/folio/search/service/metadata/ResourceDescriptionService.java, src/test/java/org/folio/search/service/LanguageConfigServiceTest.java
Tenant is able to create a language with name = src. This behavior is not correct and must be forbidden. 
src is the system field that is used only internally for all full-text values where there is no language specified or to enable searching by fields using icu_folding char filter. There is no need to specify it manually by the tenant.
- The tenant cannot create a language config
Language with name = src excluded from the list of supported languages
=> MSEARCH-162: Forbid to add language = 'src' for tenant configuration

README.md, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/circulationNote.json, src/main/resources/swagger.api/schemas/item.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/resources/samples/semantic-web-primer/items.json
The purpose of this story is to allow the user a full-text search within the item's circulation notes field.
- Case insensitive
- Word match in the Inventory item's Notes[].note (array of strings)
- Search by public notes when staff only note is set to false 
- Search by all item notes 
- Supports search in other than English languages (including CKJ languages, Arabic, Hebrew)
-Added new search fields for items.circulationNotes.note
=> MSEARCH-158 Item - support circulation notes search

Dockerfile, docker/docker-compose.yml, run.sh
Using the existing Dockerfile configuration is not efficient and does not allow to unify environment variables like `JAVA_OPTIONS`. Also, other folio Spring-based modules are using `folioci/alpine-jre-openjdk11:latest` as the root Docker image.
- Update `Dockerfile` to use `folioci/alpine-jre-openjdk11:latest` as the root Docker image
- Remove redundant `run.sh` file
- Update Docker compose file to run the application locally using Docker image
- Add to docker-compose PostgreSQL as service
=> MSEARCH-171 Update Dockerfile to use folioci java Docker image

README.md, pom.xml, src/main/java/org/folio/search/configuration/properties/FolioEnvironment.java, src/main/java/org/folio/search/configuration/properties/SearchConfigurationProperties.java, src/main/java/org/folio/search/service/SearchTenantService.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/application.yml, src/test/java/org/folio/search/configuration/properties/FolioEnvironmentTest.java, src/test/java/org/folio/search/controller/IndexingIT.java, src/test/java/org/folio/search/repository/IndexRepositoryTest.java, src/test/java/org/folio/search/repository/SearchRepositoryTest.java, src/test/java/org/folio/search/service/IndexServiceTest.java, src/test/java/org/folio/search/service/KafkaAdminServiceTest.java, src/test/java/org/folio/search/service/SearchTenantServiceTest.java, src/test/java/org/folio/search/service/converter/MultiTenantSearchDocumentConverterTest.java, src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/java/org/folio/search/utils/EnvironmentUnitTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java, src/test/java/org/folio/search/utils/TestConstants.java, src/test/resources/application.yml
Backward compatible solutions bring to Falcon a lot of problems with shared Kafka. Removing it would affect previous releases, but in the future, it will guarantee that the specified environment can receive only correct messages. Also, making the `ENV` variable mandatory can be signal for dev-ops team that something is not set up correctly.
- Remove optional ENV variable with a default value and rewrite validation to use Spring Validation instead of an imperative solution
- Remove backward-compatible approach for Kafka consumers
- Update documentation for `ENV` variable
- Add Spring configuration processor to make the configuration more developer-friendly
- Refactor configuration properties to unify with existing solutions
- Update unit tests after refactoring ENV variable
- Fix …
=> MSEARCH-172 Make ENV varialbe required and update kafka listening pattern

src/main/java/org/folio/search/controller/ApiExceptionHandler.java, src/test/java/org/folio/search/controller/ConfigControllerTest.java, src/test/java/org/folio/search/controller/IndexControllerTest.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/service/LanguageConfigServiceTest.java, src/test/java/org/folio/search/service/LocalFileProviderTest.java, src/test/java/org/folio/search/service/TenantScopedExecutionServiceTest.java, src/test/java/org/folio/search/service/setter/holding/HoldingIdentifiersProcessorTest.java, src/test/java/org/folio/search/service/setter/item/ItemIdentifiersProcessorTest.java
The reindex request has changed and requires now its body to contain the property `recreateIndex`.  When a request is sent without `content-type` header - 500 status code is returned
- Add the error handling method for `HttpMediaTypeNotSupportedException` in `ApiExceptionHandler.class`
- Increase code coverage for uncovered lines
=> MSEARCH-163 Unhandled error when reindex has empty request body

src/main/java/org/folio/search/service/IndexService.java, src/main/resources/application.yml, src/test/java/org/folio/search/service/IndexServiceTest.java
Current retry settings for failed messages are
```
application:
kafka:
retry-interval-ms: 20000
retry-delivery-attempts: 10
```
This leads that initial bulk processed with a time equal to:
```10 * 20 sec = 200 sec ```
and then, if it's failing every message is processed with the same amount of time. So the gracefully handled bulk processed with time:
```200s + 50 (amount of messages in bulk) * 10 * 20 sec = 10200 sec = 170 min```
This value must be decreased to 10 minutes to not stop the processing of messages for a long time. The current implementation will log every unprocessed message.
Kafka settings: retry-interval-ms and retry-delivery-attempts must be decreased
- `retry-interval-ms` must be set to 2000
- `retry-delivery-attempts` must be set to 6
- Make these options configurable by …
=> MSEARCH-173 Decrease the retry timeout

src/main/java/org/folio/search/controller/FolioTenantController.java, src/main/java/org/folio/search/service/SearchTenantService.java, src/test/java/org/folio/search/controller/FolioTenantControllerTest.java, src/test/java/org/folio/search/service/SearchTenantServiceTest.java
Currently, if mod-search is initialized for the tenant where DB already has instances, the user can’t find these instances. 
- new tenant attribute processing should be added
- on _**runReindex**_ modules should start reindex
New tenant attributes can be set up on environments with stub data which is created before mod-search starts. _**runReindex**_ attribute should trigger the full reindex on module start up
=> MSEARCH-174 Investigate indexing issues in reference environment

README.md, src/main/java/org/folio/search/cql/CallNumberSearchTermProcessor.java, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/service/setter/holding/HoldingsNormalizedCallNumbersProcessor.java, src/main/java/org/folio/search/service/setter/item/ItemsNormalizedCallNumbersProcessor.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/SearchHoldingsIT.java, src/test/java/org/folio/search/controller/SearchItemIT.java, src/test/java/org/folio/search/cql/CallNumberSearchTermProcessorTest.java, src/test/java/org/folio/search/service/setter/holding/HoldingsNormalizedCallNumbersProcessorTest.java, src/test/java/org/folio/search/service/setter/item/ItemsNormalizedCallNumbersProcessorTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java
<p><strong>Purpose/Overview:</strong><br /> In many cases librarians need to search for the record based on a call number that is provided by a patron and might not be formatted correctly.</p>
<p><strong>Requirements/Scope:</strong></p>
<p><strong>Example:</strong></p>
<div class="table-wrap">
Prefix | Call Number | Postfix
-- | -- | --
Rare Books | S537.N56 C82 | Incunabule
</div>
<ol>
<li>s537.N56 C82 matches&nbsp; the example</li>
<li>s537 .N56 C82 matches&nbsp; the example</li>
<li>s537.N56 C82 Incunabule matches the example</li>
<li>rare books&nbsp;s537.N56 C82 matches the example</li>
</ol>
<p><strong>Approach:</strong></p>
- Added new search term processor that should normalize and add a wildcard to the query
- Normalize tokens and save pairs prefix+callnumber+suffix and …
=> MSEARCH-169 Support normalized search for call numbers

src/main/resources/application.yml
Return missing configuration property, it has been removed by mistake from initial pull-request
=> MSEARCH-182 Disable search by all by default

README.md, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/SearchByAllFieldsIT.java
- Fix the README.md file because it contained invalid description of field options
- Rename search option from `cql.allInstance` to `cql.allInstances`
- Ad test cases for searching by date values
=> MSEARCH-182 Fix cql.allInstance option

src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/instance.json, src/test/java/org/folio/search/cql/CallNumberSearchTermProcessorTest.java, src/test/java/org/folio/search/service/ResourceIdServiceTest.java
Add a 'contributorNameTypeId' field value to unblock further development
- Add 'contributorNameTypeId' to the instance.json to be correctly indexed
- Existing integration and unit tests proves functionality
=> MSEARCH-194 Add contributorNameTypeId field for contributors

descriptors/ModuleDescriptor-template.json
Add missing Module API descriptors for the newly added endpoint `/search/holdings`
=> MSEARCH-184 Update Okapi module descriptors

README.md, src/main/java/org/folio/search/controller/ApiExceptionHandler.java, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/test/java/org/folio/search/controller/IndexControllerTest.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
`cql.allRecords=1` must return all records in Elasticsearch tenant index using `match_all` query. It would be the fastest solution to get a count of resources and any resources for the tenant.
- Extend `convertToTermQuery` method in `CqlSearchQueryConverter` to directrly convert `cql.allRecords=1` to the Elasticsearch `match_all` query
- Add integration and unit tests
=> MSEARCH-185 Implement cql.allRecords=1 search option

src/main/java/org/folio/search/service/setter/instance/AbstractPublicNotesProcessor.java, src/main/java/org/folio/search/service/setter/item/ItemPublicNotesProcessor.java, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/circulationNote.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/setter/item/ItemPublicNotesProcessorTest.java, src/test/resources/samples/semantic-web-primer/items.json
- If the circulation note is mark as staff only, it is included in notes (all) search but is not included in public notes search results
- if the circulation note is not marked as staff only, it is included in public notes search results
- the functionality introduced in MSEARCH-158 stays as it is and the user can also search for circulation notes separately
=> MSEARCH-175 Item - include circulation notes search in item notes search

docker/elasticsearch/Dockerfile, docker/elasticsearch/elasticsearch.yml, src/test/java/org/folio/search/support/extension/impl/ElasticSearchContainerExtension.java
Upgrading the Elasticsearch client version shows that integration tests can pass through, but API tests at the snapshot environment can fail.
Error message:
```
{
"errors":[
{
"message":"Invalid or missing build flavor [oss]",
"type":"ElasticsearchException",
"code":"elasticsearch_error"
}
],
"total_records":1
}
```
- Use in integration tests `amazon/opendistro-for-elasticsearch:1.13.2` docker image with pre-installed list of required plugins
- Check that integration tests pass throught
=> MSEARCH-190 Use opendistro image for integration tests

descriptors/DeploymentDescriptor-template.json, descriptors/ModuleDescriptor-template.json
The replacement tokens for Spring-based modules are different from the normal form.
Instead, they require tokens of the form: "@artifactId@-@version@"
The maven build then transforms the replacement tokens (for "artifactId" and "version") in those template descriptors, and the resultant final Descriptors are generated to "./target/ModuleDescriptor.json" etc.
- Use `@artifactId@-@version@` instead of `${artifactId}-${version}`
- Fix versions for API and json formatting of module descriptor template file
=> FOLSPRINGB-4 Fix Maven replacement tokens in descriptor templates

descriptors/ModuleDescriptor-template.json
Increase memory limits for the mod-search to prevent crushing by out of memory
- Increase memory limits in ModuleDescriptor-template.json
=> Increase memory limits

src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/EsInstanceToInventoryInstanceIT.java, src/test/resources/samples/semantic-web-primer/instance.json
Add a `discoverySuppress` and `staffSuppress` to the response.
- Add required fields to the search response
- Fix integration test to apply new fields
=> MSEARCH-223 Add discovery and stuff suppress to response

README.md, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/holding.json, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java
**Purpose/Overview:**
The purpose of this story is to provide a quick way to narrow down the search results to the specific holdings source
**Requirements/Scope:**
Holdings search based on the holdings.sourceId
**Acceptance criteria:**
Search returns accurate hit count
Search returns instances with holdings that matches specified permanent location
User can limit instances search by location data associated with holdings
=> MSEARCH-202 Holdings - filter/facet by holdings source

README.md, src/main/java/org/folio/search/model/metadata/AuthorityFieldDescription.java, src/main/java/org/folio/search/service/setter/authority/AbstractAuthorityProcessor.java, src/main/java/org/folio/search/service/setter/authority/AuthRefTypeProcessor.java, src/main/resources/model/authority.json, src/main/resources/swagger.api/schemas/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java, src/test/java/org/folio/search/service/setter/authority/AuthRefTypeProcessorTest.java, src/test/java/org/folio/search/utils/AuthoritySearchUtils.java
The results list will need to include the information that will specify where the match was found so that the user can easily identify the type of record that provides authority information. The heading type must be correctly identified based on the source of the match.
- Implement new subfield for authority field description - `authRefType`
- Implement search field `authRefType` with corresponding field processor which will populate this field with related values for further filtering
- Add a single integration test to check that new field can be used as a filter
=> MSEARCH-212 Implement Authorized/Reference field

src/main/java/org/folio/search/service/setter/authority/AbstractAuthorityProcessor.java, src/main/java/org/folio/search/service/setter/authority/HeadingRefProcessor.java, src/main/resources/model/authority.json, src/main/resources/swagger.api/schemas/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java, src/test/java/org/folio/search/service/setter/authority/HeadingRefProcessorTest.java, src/test/java/org/folio/search/utils/AuthoritySearchUtils.java
The results list will need to include the information that will specify where the match was found so that the user can easily identify the Heading/Reference of record that provides authority information.
Approach
* Implement new subfield for authority field description - `headingRef`
* This field is currently stored as `source` and it can not be searchable using queries like - `headingRef all John`
* Add a single integration test to check that new field can be used as a filter
=> MSEARCH-211 Implement Heading/Reference field

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java, src/test/resources/samples/authority-sample/authority.json
The purpose of this story is to support the Authority record search option by a personal name. The story assumes that the personalName, stfPersonalName, and saftPersonalName fields are populated with the data coming from subfields  a-d,q, g  from MARC 100, 400, and 500 fields.
- The search is based on authority record's personalName, stfPersonalName and saftPersonalName
- Change mappings type for `personalName`, `sftPersonalName` and `saftPersonalName` in resource description file from `source` …
=> MSEARCH-213 Implement searching by personal name fields

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java
The purpose of this story is to support the Authority record search option by a personal name. The story assumes that the `uniformTitle`, `stfUniformTitle`, and `saftUniformTitle` fields are populated with the data coming from  all subfields but $6 and $8 from MARC fields 130, 430 and 530 respectively.
- The search is based on authority record's `uniformTitle`, `stfUniformTitle`, and `saftUniformTitle`
- Change mappings type for `uniformTitle`, `stfUniformTitle`, and `saftUniformTitle` in …
=> MSEARCH-229 Implement searching by uniform titles

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java
The purpose of this story is to support Authority record search option by Children's subject headings.
Assumptions:
The story assumes that the subjectHeadings field is populated with the data coming from 1xx field of the record that has LDR 008 position 11 set to "b"
- The search is based on authority record's subjectHeadings
- Change mappings type for `subjectHeadings` in resource description file from `source` to `standard`
- Add integration test to check implemented functionality
=> MSEARCH-231 Implement searching by Children's subject headings fields

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java
The purpose of this story is to support Authority record search option by a topical term.
Assumptions:
The story assumes that topicalTerm, stfTopicalTerm and saftTopicalTerm fields are populated with the data coming from  all subfields but $6 and $8 from MARC fields 150, 450 and 550 respectively.
- The search is based on authority record's topicalTerm, stfTopicalTerm and saftTopicalTerm
- Change mappings type for `topicalTerm`, `sftTopicalTerm` and `saftTopicalTerm` in resource description file …
=> MSEARCH-230 Implement searching by subject field

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java
The purpose of this story is to support Authority record search option by genre.
Assumptions:
The story assumes that genreTerm, stfGenreTerm and saftGenreTerm fields are populated with the data coming from all subfields but $6 and $8 from MARC fields 155, 455 and 555 respectively.
- The search is based on authority record's genreTerm, stfGenreTerm and saftGenreTerm
- Change mappings type for `genreTerm`, `sftGenreTerm` and `saftGenreTerm` in resource description file from `source` to `standard` …
=> MSEARCH-232 Implement searching by genre term fields

Jenkinsfile, README.md
Adds the `doApiDoc` configuration to Jenkinsfile, which enables the [api-doc](https://dev.folio.org/guides/api-doc/) CI facility. This generates and publishes the API documentation during a merge to mainline and on release.
The `doUploadApidocs` is already configured for mod-search, to generate docs during the Maven build phase and then upload to S3. That is already linked from the API documentation as "view-3" (see [explain views](https://dev.folio.org/reference/api/#explain-views)).
This `doApiDoc` will generate the additional "view-4" as is done for other OAS-based modules (e.g. [mod-remote-storage](https://dev.folio.org/reference/api/#mod-remote-storage)). So mod-search will have two views of API documentation generated from the sole source API description. This is similar to …
=> FOLIO-3231 Use api-doc CI facility

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityFilterIT.java, src/test/java/org/folio/search/controller/SearchAuthorityIT.java
The purpose of this story is to support the Authority record search option by a corporate or conference name.
It's assumed that: 
- `corporateName`, `stfCorporateName` and `saftCorporateName` fields are populated with the data coming from  all subfields but $6 and $8 from MARC fields 151, 451 and 551 respectively.
- Change mappings type for `geographicName`, `sftGeographicTerm`, `saftGeographicTerm` in resource description file from `source` to `standard`
- Add integration test to check implemented functionality
=> MSEARCH-215 Implement searching by geographic name

descriptors/ModuleDescriptor-template.json
New `inventory-storage.authority.reindex.post` is missing for tenant init endpoint, which fails the tenant init operation
- Add missing permission for tenant init module
=> MSEARCH-251 Add missing permission to run reindex on tenant init

descriptors/ModuleDescriptor-template.json
New `inventory-storage.authority.reindex.post` is missing for tenant init endpoint, which fails the tenant init operation
- Add missing permission for tenant init module
=> MSEARCH-251 Fix permission name

src/main/java/org/folio/search/service/SearchService.java, src/test/java/org/folio/search/service/SearchServiceTest.java
This issues is raised by sonarcloud, however it's impossible to retrieve null value for total hits according to Elasticsearch response contract
=> Fix potential NPE issue in sonarcloud

NEWS.md, pom.xml
The 'formatMsgNoLookups' property was added in version 2.10.0, per the JIRA Issue LOG4J2-2109 that proposed it. Therefore the 'formatMsgNoLookups=true' mitigation strategy is available in version 2.10.0 and higher, but is no longer necessary with version 2.15.0, because it then becomes the default behavior .
=> MSEARCH-255 Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, pom.xml
The 'formatMsgNoLookups' property was added in version 2.10.0, per the JIRA Issue LOG4J2-2109 that proposed it. Therefore the 'formatMsgNoLookups=true' mitigation strategy is available in version 2.10.0 and higher, but is no longer necessary with version 2.16.0, because it then becomes the default behavior .
=> MSEARCH-257 Juniper R2 2021 - Log4j vulnerability verification and correction

descriptors/ModuleDescriptor-template.json
Include from mod-search.csv to allow that a user is created with those
permissions - even in case of non-existing operating user.
See https://issues.folio.org/browse/MODPERMS-172
To make _tenant init succeed in the case where operating user is not existing (for the tenant that
tenant is performed for).
Include in `modulePermissions` all the permissions that are to be assigned for the user.
=> modulePermissions include permissions for module user

src/main/java/org/folio/search/model/service/CallNumberServiceContext.java, src/main/java/org/folio/search/service/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/CallNumberBrowseIT.java, src/test/java/org/folio/search/service/CallNumberBrowseServiceTest.java
When `precedingRecordsCount` option is specified - the call number browse endpoint returns an incorrect amount of items
- Fix the typo during creating the CallNumberServiceContext object
- Update unit tests to check that everything works as expected
=> MSEARCH-253 Fix incorrect behavior when precedingRecordsCount is specified

src/main/resources/application.yml
Browsing results at snapshot and testing environment contains partial data of all uploaded instances with populated effective shelving order.
- Increase range query offset from 0.5e18 to 1e20
=> MSEARCH-253 Update default value for range query offset

src/main/java/org/folio/search/service/CallNumberBrowseService.java, src/main/resources/swagger.api/schemas/response/callNumberBrowseItem.json, src/test/java/org/folio/search/controller/CallNumberBrowseIT.java, src/test/java/org/folio/search/service/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Current implementation with highlighting result with tags can be improved by using field isAnchor with boolean value - true if the current row must be highlighted
* Add field `isAnchor` to the call number browse item entity.
* Fix integration and unit tests
=> MSEARCH-275 Implement highlighting using flag isAnchor

README.md, pom.xml, src/main/java/org/folio/search/service/setter/holding/HoldingIdentifiersProcessor.java, src/main/java/org/folio/search/service/setter/item/ItemIdentifiersProcessor.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/setter/holding/HoldingIdentifiersProcessorTest.java, src/test/java/org/folio/search/service/setter/item/ItemIdentifiersProcessorTest.java
The existing implementation of Item Identifiers (all) includes searches for items' HRIDs, Former Ids, and Accession numbers.   However, the libraries might use Item Identifiers as well, for example for a secondary remote storage identifier.
item and holding UUID added to the corresponding processors.
=> MSEARCH-272 Include Item identifier in Identifier (all) search

src/main/java/org/folio/search/model/metadata/ResourceDescription.java, src/main/java/org/folio/search/service/IndexService.java, src/main/java/org/folio/search/service/SearchTenantService.java, src/main/resources/model/instance_subject.json, src/test/java/org/folio/search/service/IndexServiceTest.java, src/test/java/org/folio/search/service/SearchTenantServiceTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Current implementation scan all resource descriptors and runs for them reindex on tenant initialization. With that change, it will be fixed and only primary resources will be reindexed, when secondary resources can exist safely.
- Add boolean flag `isPrimary` for resource descriptors
- Fix unit tests and add new to check that secondary resources won't be reindexed.
=> MSEARCH-254 Fix reindexing issue for instance_subject secondary resource

src/main/java/org/folio/search/cql/CallNumberBrowseSearchTermProcessor.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CallNumberBrowseSearchTermProcessorTest.java
Query ```callNumber = ""``` must return all results containing generated callNumber.
- Fix an issue when `CallNumberBrowseSearchTermProcessor` returns 0 for empty value
- Add unit and integration test to verify the new approach
=> MSEARCH-283 Fix call number exists query

README.md, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java
The existing implementation of Statistical code facets combines statistical codes from instances, holdings, and items into one facet on the instance record level. We need to have the facets separated by each record type
- All required configuration is already present so this pull request just adds necessary integration test cases
=> MSEARCH-285 Separate Statistical code facets for instances, holdings and items

README.md, src/main/resources/model/authority.json, src/test/java/org/folio/search/controller/SearchAuthorityIT.java
Add "saftPersonalNameTitle", "saftCorporateNameTitle" and "saftMeetingNameTitle" as search fields for Authority records.
[MSEARCH-292](https://issues.folio.org/browse/MSEARCH-292)
=> MSEARCH-292 Update Authority Search Options - Corporate/Conference Name & Personal Name

src/main/java/org/folio/search/integration/ResourceFetchService.java, src/main/java/org/folio/search/service/ResourceService.java, src/main/java/org/folio/search/utils/CollectionUtils.java, src/test/java/org/folio/search/controller/IndexingIT.java, src/test/java/org/folio/search/integration/ResourceFetchServiceTest.java, src/test/java/org/folio/search/service/ResourceServiceTest.java, src/test/java/org/folio/search/support/api/InventoryApi.java, src/test/java/org/folio/search/utils/CollectionUtilsTest.java, src/test/java/org/folio/search/utils/TestUtils.java
This pull-request fixing issue was noticed in the rancher environment when update events have been ignored
- Refactor the ResourceFetchService to pass further the old body within the new resource event
- Fix issue when ResourceService ignores UPDATE events
- Add integration test to verify that update operation works correctly
=> MSEARCH-276 Fix update operation on instance

descriptors/ModuleDescriptor-template.json
Delete tenant operation works incorrectly because module-descirptor.json contains an invalid version of tenant API
- Fix the tenant API version in ModuleDescriptor-template.json
=> FAT-1150 Update module descriptors to correctly delete tenant

README.md, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/controller/SearchItemIT.java, src/test/java/org/folio/search/service/setter/item/ItemAllFieldValuesProcessorTest.java
Remove search aliases and rename fields:
- itemsFullCallNumbers  -> itemFullCallNumbers
- itemsNormalizedCallNumbers -> itemNormalizedCallNumbers
- holdingTags ->holdingsTags
- holdingPublicNotes -> holdingsPublicNotes
- holdingIdentifiers  -> holdingsIdentifiers
- Updated documentation
- After renaming we should run reindex on all environments
https://issues.folio.org/browse/MSEARCH-298
=> MSEARCH-298 Remove backward compatibility search options

README.md, src/main/java/org/folio/search/configuration/CacheConfiguration.java, src/main/java/org/folio/search/configuration/properties/SearchCacheConfigurationProperties.java, src/main/java/org/folio/search/configuration/properties/SearchQueryConfigurationProperties.java, src/main/java/org/folio/search/controller/FolioTenantController.java, src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java, src/main/java/org/folio/search/model/service/CallNumberBrowseRangeValue.java, src/main/java/org/folio/search/service/SearchTenantService.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseQueryProvider.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseRangeService.java, src/main/resources/application.yml, src/test/java/org/folio/search/configuration/CacheConfigurationTest.java, src/test/java/org/folio/search/controller/CallNumberBrowseIT.java, src/test/java/org/folio/search/controller/FolioTenantControllerTest.java, src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java, src/test/java/org/folio/search/service/SearchTenantServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseQueryProviderTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseRangeServiceTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java, src/test/java/org/folio/search/utils/TestUtils.java, src/test/resources/application.yml
The existing browsing solution performance can be optimized by:
- Using small range query to retrieve results and then, if the result is not enough - use range query without top\lower boundaries
- Using a range aggregation request to cache numeric values intervals and use them to define appropriate lower\top boundaries
_Optmization is based on retrieving from Elasticsearch count for the interval between the first character (0-9, A-Z) of the call number, then the counts can be transformed to a list and with a special algorithm._
Steps of development:
- Implement range count uploading from Elasticsearch
- Apply algorithm to select minimal boundary value from received ranges
- Fix/update unit and integration tests
=> MSEARCH-308 Optimize call-number browsing

pom.xml, src/main/java/org/folio/search/service/ResourceIdService.java, src/test/java/org/folio/search/repository/IndexRepositoryTest.java
downgrade version of elasticsearch from 7.13.4 to 7.10.2 to match apache license
see for more details https://issues.folio.org/browse/MSEARCH-322
changed version of the elasticsearch im pom.xml
as a result made minor change in ResourceIdService.class and some changes in IndexRepositoryTest.class to match downgraded version of the elasticsearch
=> MSEARCH-322 Downgrade version of elasticsearch from 7.13.4 to 7.10.2

src/main/java/org/folio/search/service/browse/CallNumberBrowseResultConverter.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/tenantConfiguredFeature.json, src/test/java/org/folio/search/controller/CallNumberBrowseIT.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseResultConverterTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
The current implementation of call-number browsing by all schemas allows mod-search to populate new rows from the instance level items if they have shelf keys between the found value by Elasticsearch and the next value. This feature sometimes can provide a list of rows for UI with the same title and call number, which is confusing.
- Implement a new feature called - `browse.cn.intermediate.values`
- Add an integration test to validate that intermediate values can be populated
- Make this option disabled by default
=> MSEARCH-323 Make populating of intermediate shelf-keys configurable

pom.xml
When deploying mod-search and port is already in use, the service keeps running
Expected behavior: service (process) should abort/exit
- Increment the minor version of spring-kafka to fix the issue
Related issues and pull-requests:
- https://github.com/spring-projects/spring-kafka/issues/2055
- https://github.com/spring-projects/spring-kafka/pull/2060
=> MSEARCH-268 Application must stop if port is already in use

src/main/java/org/folio/search/controller/BrowseController.java, src/main/java/org/folio/search/model/BrowseResult.java, src/main/java/org/folio/search/model/SearchResult.java, src/main/java/org/folio/search/model/service/BrowseContext.java, src/main/java/org/folio/search/service/browse/AbstractBrowseService.java, src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseQueryProvider.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseResultConverter.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/main/java/org/folio/search/utils/CollectionUtils.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/swagger.api/schemas/response/authorityBrowseResult.json, src/main/resources/swagger.api/schemas/response/callNumberBrowseResult.json, src/main/resources/swagger.api/schemas/response/subjectBrowseResult.json, src/test/java/org/folio/search/controller/AuthorityBrowseIT.java, src/test/java/org/folio/search/controller/BrowseControllerTest.java, src/test/java/org/folio/search/controller/SearchAuthorityFilterIT.java, src/test/java/org/folio/search/controller/SubjectBrowseIT.java, src/test/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfterTest.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseRangeServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseResultConverterTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Next\Prev buttons must be disabled on UI if there is no data in forward\backward directions, mod-search must mark the first and last pages of browse results.
- It's impossible to mark the first and the last page because browsing operates with a term - `anchor` which is actually cursor, and `prev`/`next` values can be helpful to implement it.
- Add cursor parameters for browsing for backward and forward directions:
- **around/around_including**: the `prev` and `next` values will be filled with values for forward and backward queries if there are any records, one of them can be null or undefined if browsing in the following direction will produce zero results.
- **forward/foward_including**: only `next` value is specified, it can be null if there are no records ahead
- …
=> MSEARCH-315 Implement cursor parameters for browsing

src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java, src/main/java/org/folio/search/cql/builders/NotEqualToTermQueryBuilder.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/builders/NotEqualToTermQueryBuilderTest.java
Since the refactoring of the query builder mechanism one of operator became unsupported.
- Support `<>` operator for full-text fields and search aliases.
- Add additional integration test cases
- Fix the sonarcloud issue with regular expressions in EffectiveShelvingOrderTermProcessor.java
=> MSEARCH-331 Fix unsupported 'not' operator for search aliases

src/main/java/org/folio/search/service/setter/instance/CallNumberProcessor.java, src/test/java/org/folio/search/controller/CallNumberBrowseIT.java, src/test/java/org/folio/search/service/setter/instance/CallNumberProcessorTest.java
Call-numbers with double spaces after leading letter prevents from browsing in backward direction.
- Fix the `CallNumberProcessor` to correctly process values with double-spaces
=> MSEARCH-334 Fix the invalid search results for call-number with 2+ spaces

src/main/java/org/folio/search/service/browse/CallNumberBrowseResultConverter.java, src/test/java/org/folio/search/controller/CallNumberBrowseOtherIT.java
Some of the rows on the browsing page contains empty call-number values. It caused by invalid matching item by `effectiveShelvingOrder`.
- Fix matching of the items by the `effectiveShelvingOrder` field
- Add integration test to validate implemented matching
=> MSEARCH-336 Fix item matching for browsing

src/main/java/org/folio/search/cql/CqlTermQueryConverter.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlTermQueryConverterTest.java
Assuming that the instance title is mandatory for each resource - the wildcard query can be replaced with match_all query, which will increase the performance when the user will want to check the number of results.
- Use elasticsearch `match_all` query for input like `keyword = *`
- Add integration and unit tests to validate it
=> MSEARCH-324 Use match all query for 'keyword=*'

src/main/java/org/folio/search/utils/SearchQueryUtils.java, src/test/java/org/folio/search/utils/SearchQueryUtilsTest.java
Current query to retrieve the subject counts provides results in 4-6 second. It can be optimized by moving filters from the aggregation to the query level.
- Optimize the Elasticsearch query by adding filter query
- Add unit test to validate changes
- https://wiki.folio.org/display/FOLIJET/MSEARCH-333+Optimize+query+for+subject+browsing
=> MSEARCH-333 Optimize the query to retrieve subject counts

src/main/java/org/folio/search/service/browse/AbstractBrowseService.java, src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/AuthorityBrowseIT.java, src/test/java/org/folio/search/controller/CallNumberBrowseIT.java, src/test/java/org/folio/search/controller/SubjectBrowseIT.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java
In current implementation - for forward the previous value is null, for backward - next value is null. It can be improved by adding this value from the result list, assuming that these queries can be reached after initial request by browsing around.
- Previous and next values are calculated on the existing dataset and they are provides more comfortable way to browse the catalog
- Unit and integration test are updated with the new field values
=> MSEARCH-342 Add default prev/next values for browsing forward/backward

src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java, src/main/java/org/folio/search/model/types/ResponseGroupType.java, src/main/java/org/folio/search/service/SearchService.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseQueryProvider.java, src/main/java/org/folio/search/service/metadata/LocalSearchFieldProvider.java, src/main/java/org/folio/search/service/metadata/SearchFieldProvider.java, src/main/resources/model/authority.json, src/main/resources/model/instance.json, src/main/resources/model/instance_subject.json, src/test/java/org/folio/search/service/SearchServiceTest.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseQueryProviderTest.java, src/test/java/org/folio/search/service/metadata/LocalSearchFieldProviderTest.java
Returning required fields per feature/endpoint could allow in future customize response body to minify its size
- Replace boolean value for `showInResponse` with array of predefined response groups
- Update the related documentation and tests
=> MSEARCH-344 Implement response fields per feature/endpoint

src/main/java/org/folio/search/cql/builders/AllTermQueryBuilder.java, src/main/java/org/folio/search/model/metadata/PlainFieldDescription.java, src/main/java/org/folio/search/service/es/SearchMappingsHelper.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/elasticsearch/index-field-types.json, src/main/resources/elasticsearch/index/instance.json, src/main/resources/model/authority.json, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/cql/builders/AllTermQueryBuilderTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseQueryProviderTest.java
Issue found during Bugfest Lotus test. The keyword index, search for title, contributor, or identifier data and intended to work separately. If you combine title and contributor data, the search works. If you add one identifier that is stored in the found instance record, then the search fails (e.g. `wolves matthew 9781609383657`).
- Elasticsearch multi-match with type = `cross_fields` groups fields by it's analyzer and full match must be found in this group. Replacing cross fields with boolean query resolves this issue.
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-multi-match-query.html#cross-field-analysis
=> MSEARCH-319 Implement search across fields using operator 'and'

doc/development.md, src/main/java/org/folio/search/model/metadata/ResourceDescription.java, src/main/java/org/folio/search/service/IndexService.java, src/main/java/org/folio/search/service/SearchTenantService.java, src/main/resources/model/authority.json, src/main/resources/model/instance.json, src/test/java/org/folio/search/service/SearchTenantServiceTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Fix tenant initialization error when `runReindex=true` in `tenantParameters`
Add new reindexSupported field to resource description that indicate that resource could be reindexed
=> MSEARCH-370 Add new reindexSupported field to resource description

src/main/java/org/folio/search/configuration/KafkaConfiguration.java, src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/integration/KafkaMessageProducer.java, src/main/java/org/folio/search/service/ResourceService.java, src/main/resources/elasticsearch/index/contributor.json, src/main/resources/model/contributor.json, src/test/java/org/folio/search/controller/IndexingIT.java, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/java/org/folio/search/service/ResourceServiceTest.java, src/test/java/org/folio/search/support/api/InventoryApi.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
Fix problem when contributors are not indexed on reindex request
Move logic of contributor-events producing from Kafka listener to resource service
This happened due to contributor is not an independent entity, it's a child of an instance record. When instance records are reindexed then Kafka listener received events that contain only instance id and no data. After these events received a resource service fetch instance from /inventory-view/instances endpoint and only after that index instances and all related entities.
=> MSEARCH-371 Index contributors on reindex request

README.md, docker-compose.yml, docker/.env, docker/docker-compose.yml, src/main/java/org/folio/search/integration/KafkaMessageProducer.java, src/test/java/org/folio/search/integration/KafkaMessageProducerTest.java
Fix bug when existed contributor is not returned at Browse contributors result list when user filled field `contributorTypeText`.
Ignore `contributorTypeText` when forming contributor events. If taking this field into an account then system formes one update and one delete event, and contributor is removed from index.
=> MSEARCH-383 Change contributor events producing to ignore contributorTypeText

src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/test/java/org/folio/search/controller/ContributorBrowseIT.java
Fix the bug when the "Name type" filter doesn't account for the search query on anchor result.
Add filters from browse request to anchor-query for contributor browse
=> MSEARCH-388 Add filters to anchor-query for contributor browse

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/swagger.api/mod-search.yaml, src/test/java/org/folio/search/support/base/ApiEndpoints.java
Use the same endpoint `/search/resources/jobs/{jobId}/ids` in moduleDescriptor and OpenApi
https://issues.folio.org/browse/MSEARCH-387
=> MSEARCH-387 Not found when trying to retrieve resource job ids

src/main/java/org/folio/search/service/ResourceIdService.java, src/main/java/org/folio/search/service/ResourceIdsJobService.java, src/main/java/org/folio/search/service/ResourceIdsStreamHelper.java, src/main/java/org/folio/search/service/TenantScopedExecutionService.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
The errors like this appears when additional tenant was added:
`ERROR: relation "resource_ids_job" does not exist. (at ResourceIdService:110)`
It looks like the repository can't find the correct schema because the async job is running in transaction 
- Starting async job execution in scope of current tenant
- Separate @Async and @Transaction annotations (They can't used together)
- Add Content-Type for response. Without this header karate can't display the body response [KARATE issue](https://github.com/karatelabs/karate/issues/1024#issuecomment-1195374833)
https://issues.folio.org/browse/MSEARCH-392
=> MSEARCH-392 Stream ids job, relation doesn't exist while using multi tenant

NEWS.md, descriptors/ModuleDescriptor-template.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
mod-search uses only instance-storage, not the other two.
mod-search is not affected because the incompatible change is in the DELETE all APIs only that is not used by mod-search.
Only the okapiInterfaces need to be bumped in "requires" section of ModuleDescriptor-template.json
=> MSEARCH-418: Support interface instance-storage 9.0

.github/workflows/elasticsearch.yml, README.md, docker/elasticsearch/Dockerfile, docker/opensearch/Dockerfile, src/test/java/org/folio/search/support/extension/impl/ElasticSearchContainerExtension.java
In #cc-elasticsearch-opensearch-discussion Slack channel people asked whether mod-search can still run with an Elasticsearch server.
Provide an option to switch the search engine from OpenSearch to Elasticsearch when running the integration test phase of the build.
Note that this pull request uses Elasticsearch 7.18.5 container because the current 8.3.3 container has a change:
Since version 8.1 Elasticsearch no longer generates an empty array but an undefined property making many
unit tests fail. Upgrading Elasticseach from LTS version 7.18.5 to 8.3.3 will be handled in a separate issue and PR.
This obsoletes PR #289 that tried to combine the option and the upgrade from 7.18.5 to 8.3.3.
=> MSEARCH-415: Option for Elasticsearch integration test

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/integration/KafkaMessageProducer.java, src/main/java/org/folio/search/model/event/ContributorEvent.java, src/main/java/org/folio/search/model/index/ContributorResource.java, src/main/java/org/folio/search/repository/InstanceContributorsRepository.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/resources/elasticsearch/index/contributor.json, src/main/resources/model/contributor.json, src/main/resources/swagger.api/examples/browseContributorsResult.sample, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/contributor.json, src/main/resources/swagger.api/schemas/response/instanceContributorBrowseItem.json, src/test/java/org/folio/search/controller/BrowseContributorIT.java, src/test/java/org/folio/search/utils/TestUtils.java
It's needed to have info if a contributor is controlled by authority on browse contributors screen
- Update API schema
- Update contributor index mappings
- Update contributor indexing logic
- Update contributor browse logic
- Update browse interface version
[MSEARCH-412](https://issues.folio.org/browse/MSEARCH-412)
=> MSEARCH-412 Extend contributor's index with authority ID field

README.md, doc/browsing.md, src/main/java/org/folio/search/controller/BrowseController.java, src/main/java/org/folio/search/model/service/BrowseRequest.java, src/main/java/org/folio/search/service/browse/BrowseContextProvider.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/model/instance.json, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseControllerTest.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java
Fix searching by shelving order.
Fix browsing prev/next by shelving order.
- Remove termProcessor for `itemEffectiveShelvingOrder`
- Return to using shelving order in prev/next
- Add sub-field for browsing.
- Firstly we will browse around by call-number (`callNumber>="RR 720" or callNumber<"RR 720"`)
- Then take prev/next shelving order and browse in one direction by shelving order 
(`itemEffectiveShelvingOrder>"RR 3720"`)
=> MSEARCH-414 Browse call-numbers. Search failed when record have enumeration

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/model/authority.json, src/main/resources/swagger.api/schemas/authority.json, src/test/java/org/folio/search/controller/BrowseAuthorityIT.java, src/test/java/org/folio/search/controller/SearchAuthorityIT.java, src/test/java/org/folio/search/sample/SampleAuthorities.java, src/test/resources/samples/authority-sample/authority.json
Source File and Natural ID info are required for UI to generate $0 URI when it links an authority to a bib field.
JIRA: https://issues.folio.org/browse/MSEARCH-421
- update index mappings
- update response schemas
- update tests
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._
=> MSEARCH-421 Add sourceFileId and naturalId to authority search/browse response

docker/elasticsearch/Dockerfile
In #cc-elasticsearch-opensearch-discussion Slack channel people asked about the latest patch version.
7.17.6 has been released on 24 August 2022:
https://www.elastic.co/blog/elastic-stack-7-17-6-released
=> Bump Elasticsearch from 7.17.5 to 7.17.6

src/main/java/org/folio/search/service/ResourceService.java, src/test/java/org/folio/search/service/ResourceServiceTest.java, src/test/java/org/folio/search/utils/TestConstants.java
Remove item from old instance when moved
- Divide event into two separate when "old" instanceId differs form "new" instanceId
[MSEARCH-439](https://issues.folio.org/browse/MSEARCH-439)
=> MSEARCH-439 Transferring items from one instance to another results in multiple matches when searching

src/main/java/org/folio/search/service/browse/CallNumberBrowseResultConverter.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseResultConverterTest.java
Call-number with same instance as anchor disappears
Remove filtering intermediate items by `lower` and `upper` shelfKey. Because `lower` and `upper` depend on what anchor you are searching for;
**Example:**
Instance with Items ['A1', 'A2', 'A3']
If you are searching for 'A3' then the lower value will be 'A3'. And 'A1', 'A2' will be cut off.
This changes will not affect final size list, because we are sorting and trimming the results
https://issues.folio.org/browse/MSEARCH-456
=> MSEARCH-456 Call-number with same instance as anchor disappears

src/main/java/org/folio/search/cql/builders/AllTermQueryBuilder.java, src/test/java/org/folio/search/controller/SearchByAllFieldsIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/cql/builders/AllTermQueryBuilderTest.java, src/test/resources/samples/semantic-web-primer/instance.json
Fix '"keyword" search no longer works for a specific type of string'
Cherry-pick MSEARCH-430
[MSEARCH-465](https://issues.folio.org/browse/MSEARCH-465)
[MSEARCH-430](https://issues.folio.org/browse/MSEARCH-430)
=> MSEARCH-465 Morning Glory : specific string type in resource identifier field does not work in keyword search

src/test/java/org/folio/search/controller/BrowseContributorIT.java
Avoid random failure of Contributor browse integration test cases 
Previously test method was sorting actual retrieved result's items field by only two fields: _Name_ and _ContributorNameTypeId_. Now three more field sorting added: _TotalRecords_, _AuthorityId_ and _Items.size()_
[https://issues.folio.org/browse/MSEARCH-479](https://issues.folio.org/browse/MSEARCH-479)
=> MSEARCH-479 Stabilize contributors browse integration tests

src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/test/java/org/folio/search/controller/BrowseContributorIT.java, src/test/java/org/folio/search/controller/BrowseSubjectIT.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Fix bug when two same "Subject" values with different links are displayed as one result when browse
Modify anchor query to search for more then 1 match
=> MSEARCH-497 Anchor query result for subject browse returns >= 1 result

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/search/configuration/WebConfig.java, src/main/java/org/folio/search/controller/BrowseController.java, src/main/java/org/folio/search/model/service/BrowseRequest.java, src/main/java/org/folio/search/model/types/CallNumberType.java, src/main/java/org/folio/search/model/types/CallNumberTypeSource.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseQueryProvider.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseRangeService.java, src/main/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessor.java, src/main/java/org/folio/search/utils/CallNumberUtils.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/swagger.api/mod-search.yaml, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseQueryProviderTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseRangeServiceTest.java, src/test/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessorTest.java, src/test/resources/mappings/inventory.json
Create endpoint to support call-numbers browse by types
- Design API endpoint `/browse/call-numbers-{callNumberType}/instances` 
- Add logic to CallNumberBrowseQueryProvider and CallNumberBrowseRangeService to support new type of browse
=>  MSEARCH-515 Create endpoint to support CN browse by types

NEWS.md, src/main/resources/changelog/changelog-master.xml, src/main/resources/changelog/changes/v2.1/change_resource_ids_job_query_type.xml, src/test/java/org/folio/search/controller/StreamResourceIdsIT.java
Endpoint POST /search/resources/jobs have to be able to start a job if the query is longer than 255 characters.
- Add liquibase script to change 'query' column type to 'text'
[MSEARCH-520](https://issues.folio.org/browse/MSEARCH-520)
=> MSEARCH-520 Allow long queries for POST /search/resources/jobs

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/service/IndexService.java, src/main/java/org/folio/search/service/es/SearchSettingsHelper.java, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/indexSettings.json, src/main/resources/swagger.api/schemas/request/reindexRequest.json, src/test/java/org/folio/search/service/IndexServiceTest.java, src/test/java/org/folio/search/utils/TestConstants.java
Extend `reindex` endpoint with passing index settings
[MSEARCH-437](https://issues.folio.org/browse/MSEARCH-437)
- Add index settings to `reindex` endpoint
=> MSEARCH-437 Extend `reindex` endpoint with passing index settings

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessor.java, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/item.json, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessorTest.java
For browsing by call number type, the Item needs to appear under the Call number type specified either in the Item record or inherited from the Holdings record 
[MSEARCH-523](https://issues.folio.org/browse/MSEARCH-523)
- Use item.effectiveCallNumberComponents.typeId instead of item.itemLevelCallNumberTypeId for item call number type
- Add item.effectiveCallNumberComponents.typeId to search/browse responses
=> MSEARCH-523 Include call number type id from Holdings in Items record when not specified

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/IndexController.java, src/main/java/org/folio/search/repository/IndexRepository.java, src/main/java/org/folio/search/service/IndexService.java, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/request/updateIndexSettingsRequest.json, src/test/java/org/folio/search/controller/IndexControllerTest.java, src/test/java/org/folio/search/repository/IndexRepositoryTest.java, src/test/java/org/folio/search/service/IndexServiceTest.java
- Create endpoint to update index settings number_of_shards number_of_replicas refresh_interval
Closes: MSEARCH-436
Create endpoint to update index settings
- Add new PUT endpoint to update index settings number_of_shards number_of_replicas refresh_interval
=> MSEARCH-436 feat(reindex): Create endpoint to update index settings

src/main/java/org/folio/search/controller/IndexController.java, src/main/java/org/folio/search/service/IndexService.java, src/main/resources/elasticsearch/index/dynamicSettings.json, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/schemas/indexDynamicSettings.json, src/main/resources/swagger.api/schemas/request/updateIndexDynamicSettingsRequest.json, src/test/java/org/folio/search/controller/IndexControllerTest.java, src/test/java/org/folio/search/service/IndexServiceTest.java
Create endpoint to update index Dynamic settings
Removed numberOfShards property from the update settings endpoint as it is not available for update dynamically
Closes: MSEARCH-436
=> MSEARCH-436 feat(reindex): Create endpoint to update index Dynamic settings

NEWS.md, src/main/java/org/folio/search/integration/KafkaMessageProducer.java, src/main/java/org/folio/search/repository/InstanceSubjectRepository.java, src/test/java/org/folio/search/integration/KafkaMessageProducerTest.java, src/test/java/org/folio/search/repository/InstanceSubjectRepositoryTest.java, src/test/resources/log4j2.properties
Fix bug when the number of titles response is greater than real
For some reason, there could be a situation when the `instances` field of the subjects index is populated with a `null` value. Added actions to prevent such situations.
=> MSEARCH-526 Fix bug when number of titles response is greater than real

pom.xml, src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java, src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java
Add browse option for National Library of Medicine (NLM) call number type and for this implement normalization for NLM that follows the normalization of LC classification:
- NLM call numbers have the item call number type "National Library of Medicine classification"
- LC call numbers have the item call number type "Library of Congress classification"
_Support browsing by NLM call number type_
_Implements normalization for NLM that follows the normalization of LC classification_
_Closes: [MSEARCH-527](https://issues.folio.org/browse/MSEARCH-527)_
=> MSEARCH-527: add browse option for NLM call number type

src/main/java/org/folio/search/service/SearchTenantService.java, src/test/java/org/folio/search/controller/RecordsIndexingIT.java, src/test/java/org/folio/search/service/SearchTenantServiceTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/resources/application.yml
Delete tenant related topic when tenant is disabled
Added topic deletion part of the method together with test.
[MSEARCH-541](https://issues.folio.org/browse/MSEARCH-541)
=> MSEARCH-541: Kafka topic deletion by tenant id added when tenant disabled.

README.md, src/main/java/org/folio/search/service/converter/SearchDocumentConverter.java, src/main/java/org/folio/search/service/converter/SearchFieldsProcessor.java, src/main/java/org/folio/search/service/setter/AbstractSharedFieldProcessor.java, src/main/java/org/folio/search/service/setter/authority/AuthoritySharedFieldProcessor.java, src/main/java/org/folio/search/service/setter/instance/InstanceSharedFieldProcessor.java, src/main/resources/application.yml, src/main/resources/model/authority.json, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/authority.json, src/main/resources/swagger.api/schemas/holding.json, src/main/resources/swagger.api/schemas/instance.json, src/main/resources/swagger.api/schemas/item.json, src/main/resources/swagger.api/schemas/tenantConfiguredFeature.json, src/test/java/org/folio/search/controller/BrowseAuthorityIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberOtherIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/controller/SearchAuthorityIT.java, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/service/converter/SearchDocumentConverterTest.java, src/test/resources/application.yml, src/test/resources/log4j2.properties
TenantId and shared fields are present in the search/browse responses
TenantId and shared fields are searchable via CQL
* update mappings
* populate tenantId from Kafka message body
* populate shared from source field by CONSORTIUM- prefix
https://issues.folio.org/browse/MSEARCH-532
=> feat(consortium): add shared, tenantId flags to mapping

src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/BrowseAroundCallNumberIT.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java
Optimize result building to use already queried data before querying new
Improve preceding records searching 
Closes: MSEARCH-552, MSEARCH-544
- Change condition for additionalPrecedingRequests to check the size of records
- Avoid additionalPrecedingRequests if backwardSucceedingResult contains required records
- Improve test case for "preceding" records and add new for "succeeding" records
=> fix(cn-browse): Improve preceding records searching

NEWS.md, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/integration/KafkaMessageProducer.java, src/main/java/org/folio/search/model/index/ContributorResource.java, src/main/java/org/folio/search/model/index/InstanceSubResource.java, src/main/java/org/folio/search/model/index/SubjectResource.java, src/main/java/org/folio/search/repository/InstanceContributorsRepository.java, src/main/java/org/folio/search/repository/InstanceSubjectRepository.java, src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/BrowseContextProvider.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/main/java/org/folio/search/service/converter/preprocessor/AuthorityEventPreProcessor.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/model/contributor.json, src/main/resources/model/instance_subject.json, src/test/java/org/folio/search/controller/BrowseContributorConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseContributorIT.java, src/test/java/org/folio/search/controller/BrowseSubjectConsortiumIT.java, src/test/java/org/folio/search/controller/RecordsIndexingIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/repository/InstanceContributorsRepositoryTest.java, src/test/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfterTest.java, src/test/java/org/folio/search/service/browse/ContributorBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java, src/test/java/org/folio/search/service/converter/preprocessor/AuthorityEventPreProcessorTest.java, src/test/java/org/folio/search/utils/AuthoritySearchUtils.java, src/test/java/org/folio/search/utils/TestUtils.java
Add tenantId/shared fields to contributors/subjects so they could be used as filters for browsing
[MSEARCH-551](https://issues.folio.org/browse/MSEARCH-551)
- Fix active affiliation query for central tenant
- Remove tenantId from constructing id for subjects/contributors
- Add tenantId/shared flags to contributors/subjects indexing
- Add authority shared flag population
- Update contributors/subjects upsert scripts
=> feat(consortium): Add tenantId/shared fields to contributors/subjects

src/main/resources/model/contributor.json, src/main/resources/model/instance_subject.json
Fix retrieving contributors without 'shared' flag
[MSEARCH-551](https://issues.folio.org/browse/MSEARCH-551)
Set default 'shared' value to false for subjects/contributors
=> fix(consortium) Set default value for 'shared' field on subjects/constributors

NEWS.md, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java
Restrict Central tenant search and browse results to ONLY Shared records
Restrict central tenant queries to only shared records
https://issues.folio.org/browse/MSEARCH-588
=> feat(consortium): Restrict central tenant queries to only shared records

src/main/java/org/folio/search/model/event/ConsortiumInstanceEvent.java, src/main/java/org/folio/search/service/consortium/ConsortiumTenantService.java
Fix a problem when records created in central tenant are sometimes saved as local
[MSEARCH-590](https://issues.folio.org/browse/MSEARCH-590)
Add context tenantId to a cache key for /user-tenants response
=> fix(consortium) Fix records created in central tenant are sometimes saved as local

NEWS.md, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/model/index/SubjectResource.java, src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/BrowseContextProvider.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseQueryProvider.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java, src/test/java/org/folio/search/controller/BrowseContributorConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseSubjectConsortiumIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseQueryProviderTest.java, src/test/java/org/folio/search/service/browse/ContributorBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java, src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java
Implement active affiliation context for browse so it works together with instances.shared filter
[MSEARCH-580](https://issues.folio.org/browse/MSEARCH-580)
- Move consortium filtering logic into a new class ConsortiumSerachHelper
- Add active affiliation logic for browse authorities/call numbers/subjects/contributors
- Add active affiliation logic to sub-resource result filtration on subjects/contributors
=> feat(consortium): Implement active affiliation context for browse

descriptors/ModuleDescriptor-template.json
Add missed authority-reindex interface to module descriptor
=> fix(reindex): Add missed authority-reindex interface to module descriptor

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/FacetsController.java, src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseQueryProvider.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/main/java/org/folio/search/service/consortium/ConsortiumInstanceService.java, src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java, src/main/resources/dev-log4j2.properties, src/main/resources/model/contributor.json, src/main/resources/model/instance.json, src/main/resources/model/instance_subject.json, src/main/resources/swagger.api/mod-search.yaml, src/test/java/org/folio/search/controller/BrowseContributorConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseSubjectConsortiumIT.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseQueryProviderTest.java, src/test/java/org/folio/search/service/browse/ContributorBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java, src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java, src/test/java/org/folio/search/support/api/InventoryApi.java
Add new facets for shared/local flag and tenantId
- update elastic mappings
- add `subjects` option for facet request
https://issues.folio.org/browse/MSEARCH-534
=> feat(consortium): Add new facets for shared/local flag and tenantId

src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberOtherIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIrrelevantResultIT.java, src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Fix browsing for not specified/local call number types
[MSEARCH-569](https://issues.folio.org/browse/MSEARCH-569)
- Always add normilized call number to list of possible anchors
- Fix test data for tests by providing proper shelf keys for indexing
- Fix BrowseTypedCallNumberIT by using valid call numbers for types
=> fix(cn-browse): Fix browsing for not specified call number type

src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/BrowseAroundCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIrrelevantResultIT.java
Fix missing some of preceding records
[MSEARCH-575](https://issues.folio.org/browse/MSEARCH-575)
Add additional preceding result sort before constructing a response
=> fix(cn-browse): Fix sorting for preceding records

src/main/java/org/folio/search/model/types/CallNumberTypeSource.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/java/org/folio/search/utils/CallNumberUtils.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIrrelevantResultIT.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/utils/CallNumberUtilsTest.java, src/test/resources/mappings/inventory.json
Fix 'folio' source call numbers returned when browsing for 'local'
[MSEARCH-570](https://issues.folio.org/browse/MSEARCH-570)
- Get call number types with source="folio" from mod-inventory-storage
- Filter browse results not to include "folio" source when browsing for "local"
=> fix(cn-browse): Fix 'folio' source call numbers returnd when browsing for 'local'

src/main/java/org/folio/search/utils/CallNumberUtils.java, src/test/java/org/folio/search/utils/CallNumberUtilsTest.java
Remove not typed call numbers from "local" call numbers browse result
[MSEARCH-570](https://issues.folio.org/browse/MSEARCH-570)
Add filter on not typed call number when browse local
=> fix(cn-browse): Add filter on not typed call number when browse local

src/main/java/org/folio/search/integration/ReferenceDataService.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessor.java, src/test/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessorTest.java
Fix local call numbers not shown in result list for browsing by "local" call number type
[MSEARCH-601](https://issues.folio.org/browse/MSEARCH-601)
Query "folio" source call numbers and consider call number "local" if absent in list
=> fix(cn-browse) Fix local typed call numbers not being indexing because of old cache

pom.xml, src/main/java/org/folio/search/cql/CqlTermQueryConverter.java, src/main/java/org/folio/search/cql/builders/AllTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/AnyTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/EqualTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/ExactTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/GtTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/GteTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/LtTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/LteTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/NotEqualToTermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/TermQueryBuilder.java, src/main/java/org/folio/search/cql/builders/WildcardTermQueryBuilder.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/cql/CqlTermQueryConverterTest.java, src/test/java/org/folio/search/cql/builders/AllTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/AnyTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/EqualTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/ExactTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/GtTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/GteTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/LtTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/LteTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/NotEqualToTermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/TermQueryBuilderTest.java, src/test/java/org/folio/search/cql/builders/WildcardTermQueryBuilderTest.java, src/test/java/org/folio/search/utils/TestConstants.java
The "Exact full match" operator ( ==/string )doesn't work for alias fields.
Alias fields are replaced with a 'plan_' prefix.
**Query before changes:**
"query" : "Sit how you want / Robin Richardson.",
"fields" : [
"alternativeTitles.alternativeTitle.*^1.0",
"contributors.name^1.0",
"identifiers.value^1.0",
"indexTitle.*^1.0",
"series.value.*^1.0",
"title.*^1.0"
],
"type": "phrase"
}
**Query after changes:**
"multi_match" : {
"query" : "Sit how you want / Robin Richardson.",
"fields" : [
"alternativeTitles.plain_alternativeTitle^1.0",
"contributors.plain_name^1.0",
"identifiers.plain_value^1.0",
"plain_indexTitle^1.0",
"plain_title^1.0",
"series.plain_value^1.0"
],
"type": "phrase"
}
https://issues.folio.org/browse/MSEARCH-589
=> MSEARCH-589 "Exact full match" operator doesn't work for alias fields

src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java, src/main/java/org/folio/search/utils/CallNumberUtils.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIrrelevantResultIT.java, src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java, src/test/java/org/folio/search/utils/CallNumberUtilsTest.java
Don't show browse items from other tenants for "holdings.tenantId" filter
[MSEARCH-603](https://issues.folio.org/browse/MSEARCH-603)
Filter browse result based on holdings.tenantId filter
=> fix(cn-browse): Filter browse result based on holdings.tenantId filter

src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java
Fix irrelevant call number types are shown wneh browsing previous pages for typed call numbers
Fix result filtering for browse in one direction
=> fix(cn-browse): Fix filtering results for browse in one direction

src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java, src/main/java/org/folio/search/utils/CallNumberUtils.java, src/test/java/org/folio/search/utils/CallNumberUtilsTest.java
Fix irrelevant results on multiple location filters
Fix result filtering for multiple items.effectiveLocationId
=> fix(cn-browse): Fix result filtering for multiple items.effectiveLocationId

pom.xml
https://issues.folio.org/browse/MSEARCH-629
Upgrade Kafka from 3.4.1 to 3.5.1.
This indirectly upgrades snappy-java from 1.1.8.4 to 1.1.10.1 fixing security vulnerabilities:
https://security.snyk.io/package/maven/org.xerial.snappy:snappy-java
=> MSEARCH-629: Kafka 3.5.1, snappy-java 1.1.10.1 fixing vulns

NEWS.md, src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/utils/SearchConverterUtils.java, src/test/java/org/folio/search/integration/KafkaMessageListenerTest.java
While trigger authority reindex for member tenants - shadow copies are overwrite central tenant authorities.
Ignore authority shadow copies while indexing
https://issues.folio.org/browse/MSEARCH-638
=> fix(consortium): ignore authority shadow copies while indexing 

NEWS.md, src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/BrowseAroundCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberOtherIT.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Return result only for desired cn type. Return empty result with shelf key for passed cn type or normalized call number when no exact match.
- Browse only for shelving order using desired cn type
- Browse for multiple anchors (shelf keys generated using different algorithms) only if cn type not passed
[MSEARCH-605](https://issues.folio.org/browse/MSEARCH-605)
Test case scenario from a task showed a case when browsing for not typed call numbers and empty result returned with shelf key generated using LcCallNumber algorithm and browse result itself was returned for browsing on same shelf key in elasticsearch which is incorrect in a case when no cn is passed. Now when call number is passed we will always look for exact match using one algorithm. When call number type is not passed - we will …
=> fix(cn-browse): Return result only for desired cn type

src/main/java/org/folio/search/service/setter/authority/LccnProcessor.java, src/test/resources/mappings/inventory.json
"LCCN" option should search only by "LCCN" field ("010 $a", "010 $z")
Removed additional identifier types: "Control number", "Other standard identifier", "System control number"
Updated LccnProcessor to populate lccn field with only "LCCN" identifier type
https://issues.folio.org/browse/MSEARCH-630
=> refactor(LCCN search): search only by "LCCN" field ("010 $a", "010 $z")

src/main/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessor.java, src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java, src/test/java/org/folio/search/utils/TestUtils.java
Fix no exact match for some of Dewey call numbers
Trim search term for typed browse
[MSEARCH-643](https://issues.folio.org/browse/MSEARCH-643)
[MSEARCH-618](https://issues.folio.org/browse/MSEARCH-618) - introduced a problem
New term processor method was introduced in 618 and it was missing term trimming in the end
=> fix(cn-browse): Trim search term for typed browse

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/configuration/properties/SearchConfigurationProperties.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/resources/application.yml, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java
Make maximum offset for additional elasticsearch request on browse configurable
[MSEARCH-641](https://issues.folio.org/browse/MSEARCH-641)
Maximum query size was also limited, to 800 because it's maximum size for previous approach. So now only offset will grow when maximum size is reached
=> MSEARCH-641 Make maximum offset for additional elasticsearch request on browse configurable

NEWS.md, src/main/java/org/folio/search/integration/KafkaMessageProducer.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/test/java/org/folio/search/integration/KafkaMessageProducerTest.java
Shared Instance record and each "Shadow" copy are counted in "Number of titles" for subjects and contributors browse
* Skip indexing subjects and contributors for shadow copies
* Calclualte only unique instance ids 
* May also fix calculating null values
https://issues.folio.org/browse/MSEARCH-647
https://issues.folio.org/browse/MSEARCH-642
=> fix(consortium): fix shadow instance's subjects/contributors indexing

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/service/ResourceIdsJobService.java, src/main/java/org/folio/search/service/consortium/ConsortiumTenantExecutor.java, src/test/java/org/folio/search/controller/StreamResourceIdsIT.java
_POST /search/resources/jobs  endpoint takes much time for a query that matches 200k > records_
_Make streaming of the resources run in async mode._
[MSEARCH-685](https://folio-org.atlassian.net/browse/MSEARCH-685)
=> MSEARCH-685: Fix POST /search/resources/jobs to make it work asynchronously

src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/test/java/org/folio/search/controller/ConfigIT.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
Reference data cache should be invalidated on receiving classification-type domain event.
https://folio-org.atlassian.net/browse/MSEARCH-683
=> fix(browse-classifications): invalidate reference-data cache for classification-type event

src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/service/browse/CallNumberBrowseServiceTest.java
Fix a problem of not being able to go to the previous page
Do not construct a shelf key from anchor if anchor is already a shelf key
[MSEARCH-704](https://folio-org.atlassian.net/browse/MSEARCH-704)
Create 6 Dewey call numbers, browse for "Slava pag 6", not existing
Click on "Previous" button
Result before fix, all created call numbers displayed:
Result after fix, only numbers preceding first result of the browse page are displayed:
=> fix(cn-browse): Fix browsing in one direction by shelving order

src/main/resources/model/location.json
mark location index as not supported by reindex
As reindex for location is not supported yet, it should be disabled.
https://folio-org.atlassian.net/browse/MSEARCH-703
=> fix(search-locations): mark location index as not supported by reindex

NEWS.md, pom.xml
Do not delete kafka topics if tenant collection topic feature is enabled
Update to newest folio-service-tools version
https://folio-org.atlassian.net/browse/MSEARCH-725
=> fix: do not delete kafka topics if collection topic is enabled

src/main/java/org/folio/search/service/setter/item/CallNumberTypeProcessor.java, src/test/java/org/folio/search/controller/BrowseCallNumberConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseTypedCallNumberIT.java, src/test/java/org/folio/search/integration/KafkaMessageListenerIT.java, src/test/java/org/folio/search/service/setter/item/CallNumberTypeProcessorTest.java, src/test/java/org/folio/search/utils/TestConstants.java
Fix call number type facet filter.
- Fetch reference data for "folio" source call number types instead of local to determine if type is local
Reference data is cached for one hour so when new local call number type is created it will be absent in cache. Using folio call number types eliminates this problem as folio types couldn't be created from a UI.
[MSEARCH-738](https://folio-org.atlassian.net/browse/MSEARCH-738)
=> fix(facets): Fix facets for local call number types

NEWS.md, PULL_REQUEST_TEMPLATE.md, src/main/java/org/folio/search/service/setter/AbstractLccnProcessor.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/test/java/org/folio/search/service/setter/authority/LccnAuthorityProcessorTest.java, src/test/java/org/folio/search/service/setter/instance/LccnInstanceProcessorTest.java, src/test/java/org/folio/search/utils/SearchUtilsTest.java
Remove ability to match on LCCN searches without a prefix
- Remove additional numeric token creation in lccn processor
[MSEARCH-752](https://folio-org.atlassian.net/browse/MSEARCH-752)
=> feat(search-instances-authorities): Remove ability to match on LCCN searches without a prefix

NEWS.md, src/main/java/org/folio/search/configuration/AsyncConfig.java, src/main/java/org/folio/search/service/ResourceIdService.java, src/main/java/org/folio/search/service/ResourceIdsJobService.java, src/main/java/org/folio/search/service/consortium/ConsortiumTenantExecutor.java, src/test/java/org/folio/search/service/ResourceIdServiceTest.java
Fix issues when the ids job is never completed. 
Keep context in the stream id thread.
[MSEARCH-754](https://folio-org.atlassian.net/browse/MSEARCH-754)
=> fix(search-ids): keep right context in resource-id thread

src/main/java/org/folio/search/service/consortium/ConsortiumInstanceRepository.java, src/main/java/org/folio/search/service/consortium/ConsortiumInstanceService.java
Clean-up is too long
use truncate instead delete for db table clean-up 
[MSEARCH-744](https://folio-org.atlassian.net/browse/MSEARCH-744)
https://www.geeksforgeeks.org/difference-between-delete-and-truncate/
=> fix: use truncate instead delete for db table clean-up

NEWS.md, src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/test/java/org/folio/search/controller/BrowseAuthorityIT.java, src/test/java/org/folio/search/controller/BrowseContributorConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseContributorIT.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java
Fix duplicate results in exact match with diacritics while browsing
Use `sort` result values from anchor search response as values for `searchAfter`
With this approach we will use already processed by search engine value
[MSEARCH-751](https://folio-org.atlassian.net/browse/MSEARCH-751)
=> fix(browse): duplicate results in exact match with diacritics

src/main/java/org/folio/search/repository/SearchRepository.java, src/main/java/org/folio/search/service/browse/AbstractBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/AuthorityBrowseService.java, src/main/java/org/folio/search/service/browse/ContributorBrowseService.java, src/main/java/org/folio/search/service/browse/SubjectBrowseService.java, src/test/java/org/folio/search/controller/BrowseAuthorityIT.java, src/test/java/org/folio/search/service/browse/AuthorityBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/ContributorBrowseServiceTest.java, src/test/java/org/folio/search/service/browse/SubjectBrowseServiceTest.java
Fix browse issue when input term with diacritics are set to the end of the list in case when there is no match.
Use analyze api to get anchor for browse
[MSEARCH-751](https://folio-org.atlassian.net/browse/MSEARCH-751)
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html
=> fix(browse): use analyze api to get anchor for browse

src/main/resources/swagger.api/parameters/batchIdsDto.yaml, src/test/java/org/folio/search/controller/ConsortiumSearchHoldingsIT.java, src/test/java/org/folio/search/controller/ConsortiumSearchItemsIT.java
Limit number of ids passed to consortium batch items/holdings apis
[MSEARCH-759](https://folio-org.atlassian.net/browse/MSEARCH-759)
[search-settings](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-settings.html)
=> fix(consortium-search): Limit number of ids passed to consortium batch items/holdings apis

NEWS.md, src/main/java/org/folio/search/repository/classification/InstanceClassificationJdbcRepository.java, src/main/java/org/folio/search/service/converter/preprocessor/InstanceEventPreProcessor.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/test/java/org/folio/search/service/converter/preprocessor/InstanceEventPreProcessorTest.java
_Shared facet shows incorrect count for the shared/non shared instances_
_Handle the instance update event for sharing the instance appropriately_
[MSEARCH-761](https://folio-org.atlassian.net/browse/MSEARCH-761)
=> MSEARCH-761: Fix Instances count in Shared facet

NEWS.md, README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/SearchController.java, src/main/java/org/folio/search/integration/KafkaMessageListener.java, src/main/java/org/folio/search/integration/interceptor/ResourceEventBatchInterceptor.java, src/main/java/org/folio/search/service/setter/bibframe/authority/BibframeAuthorityLccnProcessor.java, src/main/java/org/folio/search/utils/SearchUtils.java, src/main/resources/application.yml, src/main/resources/elasticsearch/index/bibframe-authority.json, src/main/resources/model/bibframe_authority.json, src/main/resources/swagger.api/examples/result/bibframeSearchAuthorityResult.yaml, src/main/resources/swagger.api/mod-search.yaml, src/main/resources/swagger.api/paths/search-bibframe/search-bibframe-authorities.yaml, src/main/resources/swagger.api/schemas/dto/bibframe/bibframeAuthority.yaml, src/main/resources/swagger.api/schemas/response/bibframeSearchAuthorityResult.yaml, src/test/java/org/folio/search/controller/SearchBibframeAuthorityIT.java, src/test/java/org/folio/search/controller/SearchControllerTest.java, src/test/java/org/folio/search/integration/KafkaMessageListenerTest.java, src/test/java/org/folio/search/sample/SampleBibframe.java, src/test/java/org/folio/search/support/base/ApiEndpoints.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java, src/test/java/org/folio/search/utils/TestConstants.java, src/test/java/org/folio/search/utils/TestUtils.java, src/test/resources/application.yml, src/test/resources/samples/bibframe/authority_concept.json, src/test/resources/samples/bibframe/authority_person.json
add bibframe authority index for mod-linked-data module
add a new kafka topic with new data for bibframe authority index
- add new endpoint /search/bibframe/authority
- add kafka-listener for search.bibframe-authorities topic
- 
[MSEARCH-784] (https://folio-org.atlassian.net/browse/MSEARCH-784)
=> [MSEARCH-784] add bibframe authority index

descriptors/ModuleDescriptor-template.json
Searching for linked data resources fails due to HTTP 403 error in Beta test environment. From the logs it is clear that the ```user-tenants.collection.get``` permission is required.
Module permission ```user-tenants.collection.get``` has been added for the following two APIs in mod-search’s Module descriptor:
- /search/linked-data/works
- /search/linked-data/authorities
[MSEARCH-819](https://folio-org.atlassian.net/browse/MSEARCH-819)
=> [MSEARCH-819] Add module permissions for linked-data APIs

src/main/java/org/folio/search/service/consortium/ConsortiumInstanceSearchService.java, src/main/java/org/folio/search/utils/IdentifierUtils.java, src/main/resources/swagger.api/parameters/batchIdsDto.yaml, src/test/java/org/folio/search/controller/ConsortiumSearchHoldingsIT.java
[[MSEARCH-809] Extend batch holdings search endpoint with filtering by instanceId](https://folio-org.atlassian.net/browse/MSEARCH-809)
- Add instanceId as an identifier type
Verification in Jira comment: https://folio-org.atlassian.net/browse/MSEARCH-809?focusedCommentId=223845
=> [MSEARCH-809] Extend batch holdings search endpoint with filtering by instanceId

NEWS.md, README.md, src/main/java/org/folio/search/service/IndexService.java, src/main/resources/model/linked_data_authority.json, src/main/resources/model/linked_data_work.json, src/main/resources/swagger.api/schemas/request/reindexRequest.yaml, src/test/java/org/folio/search/controller/IndexManagementIT.java, src/test/java/org/folio/search/service/IndexServiceTest.java, src/test/java/org/folio/search/support/base/BaseIntegrationTest.java
… and linked-data-authority
The purpose of this pull request is to incorporate the indices recreation functionality into the Linked Data module. The Linked Data module needs the ability to reset its indexes in scenarios where a change to the system requires re-indexing the data graph, so that the indices reflect that changes introduced into the application.
```POST [OKAPI_URL]/search/index/inventory/reindex``` endpoint is being used to recreate ```linked-data-work``` and ```linked-data-authority``` resources' indices.
[MSEARCH-820](https://folio-org.atlassian.net/browse/MSEARCH-820)
=> feat: add indices recreation possibility for linked-data-work and linked-data-authority

NEWS.md, README.md, src/main/java/org/folio/search/service/setter/instance/Date1FieldProcessor.java, src/main/resources/elasticsearch/index-field-types.json, src/main/resources/model/instance.json, src/main/resources/swagger.api/schemas/dto/instance/dates.yaml, src/main/resources/swagger.api/schemas/entity/instance.yaml, src/test/java/org/folio/search/controller/SearchByAllFieldsIT.java, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java, src/test/java/org/folio/search/controller/SearchInstanceIT.java, src/test/java/org/folio/search/controller/SortInstanceIT.java, src/test/java/org/folio/search/service/setter/instance/Date1FieldProcessorTest.java, src/test/resources/samples/instance-response-sample/instance-basic-response.json, src/test/resources/samples/instance-response-sample/instance-full-response.json, src/test/resources/samples/semantic-web-primer/instance.json
[MSEARCH-806](https://folio-org.atlassian.net/browse/MSEARCH-806) Currently in the Instance schema, there is a field for publication date. However, this data originates from an uncontrolled string in variable fields of the MARC record. The dates in the 008 are more consistently formatted, and are more useful for certain materials like serials. Previously, we implemented sortable properties (publicationPeriod.start/publicationPeriod.end) that are parsed from the publication date field. We need to break this relationship, and instead make the source of that data the 07-14 from the 008. The 008 structure allows for a single position to indicate the type of date that will be represented in the following positions.
008/06 = Date type
008/07-10 = Date 1
008/11-14 = Date 2
For this story, we …
=> feat(instance-search): create computed field for sorting and filtering Date1

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/search/controller/SearchConsortiumController.java, src/main/java/org/folio/search/repository/ConsortiumCampusRepository.java, src/main/java/org/folio/search/repository/ConsortiumInstitutionRepository.java, src/main/java/org/folio/search/repository/ConsortiumLibraryRepository.java, src/main/java/org/folio/search/service/consortium/ConsortiumCampusService.java, src/main/java/org/folio/search/service/consortium/ConsortiumInstitutionService.java, src/main/java/org/folio/search/service/consortium/ConsortiumLibraryService.java, src/main/resources/swagger.api/parameters/id-query-param.yaml, src/main/resources/swagger.api/paths/search-consortium/search-consortium-campuses.yaml, src/main/resources/swagger.api/paths/search-consortium/search-consortium-institutions.yaml, src/main/resources/swagger.api/paths/search-consortium/search-consortium-libraries.yaml, src/main/resources/swagger.api/schemas/entity/consortiumCampus.yaml, src/main/resources/swagger.api/schemas/entity/consortiumInstitution.yaml, src/main/resources/swagger.api/schemas/entity/consortiumLibrary.yaml, src/test/java/org/folio/search/controller/ConsortiumSearchCampusesIT.java, src/test/java/org/folio/search/controller/ConsortiumSearchInstitutionsIT.java, src/test/java/org/folio/search/controller/ConsortiumSearchLibrariesIT.java, src/test/java/org/folio/search/repository/ConsortiumCampusRepositoryTest.java, src/test/java/org/folio/search/repository/ConsortiumInstitutionRepositoryTest.java, src/test/java/org/folio/search/repository/ConsortiumLibraryRepositoryTest.java, src/test/java/org/folio/search/service/consortium/ConsortiumCampusServiceTest.java, src/test/java/org/folio/search/service/consortium/ConsortiumInstitutionServiceTest.java, src/test/java/org/folio/search/service/consortium/ConsortiumLibraryServiceTest.java
Extend consortium library, campus, institution API with id param.
- Extend library, campus, institution endpoints with filter by id option. 
[MSEARCH-855](https://folio-org.atlassian.net/browse/MSEARCH-855)
=> MSEARCH-855: Update consortium library, campus, institution endpoints

src/main/java/org/folio/search/cql/CqlSearchQueryConverter.java, src/test/java/org/folio/search/controller/SearchInstanceFilterIT.java
Fix range query convertions when other filters present
Move range query collapsing on the latest stage of conversion, iterate through all range queries to find ones suitable for collapsing
[MSEARCH-845](https://folio-org.atlassian.net/browse/MSEARCH-845)
=> fix(search-instances): Fix range query convertions when other filters present

NEWS.md, src/main/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessor.java, src/test/java/org/folio/search/service/setter/item/ItemTypedCallNumberProcessorTest.java
Remove shelving order calculation for local types. It may slowdown indexing on ECS setup.
https://folio-org.atlassian.net/browse/MSEARCH-878
=> fix(cn-browse): remove shelving order calculation for local types

NEWS.md, src/main/java/org/folio/search/model/entity/InstanceCallNumberEntityAgg.java, src/main/java/org/folio/search/model/index/CallNumberResource.java, src/main/java/org/folio/search/model/index/InstanceSubResource.java, src/main/java/org/folio/search/model/types/ReindexEntityType.java, src/main/java/org/folio/search/model/types/ResourceType.java, src/main/java/org/folio/search/service/ResourceService.java, src/main/java/org/folio/search/service/converter/preprocessor/extractor/impl/CallNumberResourceExtractor.java, src/main/java/org/folio/search/service/reindex/ReindexConstants.java, src/main/java/org/folio/search/service/reindex/jdbc/CallNumberRepository.java, src/main/java/org/folio/search/service/setter/callnumber/CallNumberShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/callnumber/DefaultCallNumberShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/callnumber/DeweyCallNumberShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/callnumber/LcCallNumberShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/callnumber/NlmCallNumberShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/callnumber/SudocCallNumberShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/classification/ClassificationShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/service/setter/common/shelving/ShelvingOrderFieldProcessor.java, src/main/java/org/folio/search/utils/CallNumberUtils.java, src/main/resources/elasticsearch/index/instance_call_number.json, src/main/resources/model/instance_call_number.json, src/main/resources/swagger.api/schemas/request/reindexUploadDto.yaml, src/test/java/org/folio/search/service/reindex/jdbc/CallNumberRepositoryIT.java, src/test/java/org/folio/search/service/setter/classification/ClassificationShelvingOrderFieldProcessorTest.java, src/test/resources/sql/populate-call-numbers.sql
Implement Indexing and Re-indexing Mechanisms for Call-Numbers
- define index mapping
- adjust extractors and repository to save and fetch call-numbers
https://folio-org.atlassian.net/browse/MSEARCH-864
=> feat(cn-browse): Implement Indexing and Re-indexing Mechanisms for Call-Numbers

NEWS.md, src/main/java/org/folio/search/service/config/BrowseConfigService.java
Fix inconsistent classification browse on browse config update
Delete all browse config cache keys  on browse config upsert
[MSEARCH-897](https://folio-org.atlassian.net/browse/MSEARCH-897)
=> fix(browse): Fix old browse config returned on get after upsert

src/main/java/org/folio/search/service/reindex/jdbc/CallNumberRepository.java, src/test/java/org/folio/search/controller/BrowseCallNumberConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/service/reindex/jdbc/CallNumberRepositoryIT.java, src/test/resources/sql/populate-call-numbers.sql
- User should see call numbers on shared instances (should see call-numbers from items that are connected to shared instances)
- User should see call numbers on both shared and local instances
adjust populating shared field to be based on instance tenant id
https://folio-org.atlassian.net/browse/MSEARCH-939
=> fix(cn-browse): adjust populating shared field to be based on instance tenant id 

NEWS.md, README.md, src/main/java/org/folio/search/cql/CqlTermQueryConverter.java, src/main/java/org/folio/search/cql/builders/ExactTermQueryBuilder.java, src/main/java/org/folio/search/cql/searchterm/CallNumberSearchTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/CallNumberTypeIdSearchTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/ClassificationNumberSearchTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/EffectiveShelvingOrderTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/IsbnSearchTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/LccnSearchTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/OclcSearchTermProcessor.java, src/main/java/org/folio/search/cql/searchterm/SearchTermProcessor.java, src/main/java/org/folio/search/utils/SearchQueryUtils.java, src/main/resources/model/instance_call_number.json, src/main/resources/swagger.api/examples/result/browseCallNumberResult.yaml, src/main/resources/swagger.api/parameters/instance-call-number-browse-cql-query.yaml, src/main/resources/swagger.api/paths/browse-call-numbers/browse-instance-call-numbers.yaml, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/cql/CallNumberSearchTermProcessorTest.java, src/test/java/org/folio/search/cql/ClassificationNumberSearchTermProcessorTest.java, src/test/java/org/folio/search/cql/CqlSearchQueryConverterTest.java, src/test/java/org/folio/search/cql/CqlTermQueryConverterTest.java, src/test/java/org/folio/search/cql/EffectiveShelvingOrderTermProcessorTest.java, src/test/java/org/folio/search/cql/IsbnSearchTermProcessorTest.java, src/test/java/org/folio/search/cql/LccnSearchTermProcessorTest.java, src/test/java/org/folio/search/cql/OclcSearchTermProcessorTest.java, src/test/java/org/folio/search/cql/builders/ExactTermQueryBuilderTest.java, src/test/java/org/folio/search/service/browse/LegacyCallNumberBrowseServiceTest.java, src/test/java/org/folio/search/utils/SearchQueryUtilsTest.java
Support call-number browse option names as aliases for callNumberTypeId filters for call-number documents.
Add search term processor for call-number type id field.
Modify query construction for exact match term queries to support array of values.
https://folio-org.atlassian.net/browse/MSEARCH-942
=> feat(cn-browse): support aliases for callNumberTypeId filters

NEWS.md, src/main/java/org/folio/search/model/index/InstanceSubResource.java, src/main/java/org/folio/search/service/browse/AbstractShelvingOrderBrowseServiceBySearchAfter.java, src/main/java/org/folio/search/service/browse/CallNumberBrowseService.java, src/main/java/org/folio/search/service/consortium/ConsortiumSearchHelper.java, src/main/java/org/folio/search/service/reindex/jdbc/CallNumberRepository.java, src/main/java/org/folio/search/service/setter/callnumber/CallNumberSearchResponsePostProcessor.java, src/main/java/org/folio/search/utils/CallNumberUtils.java, src/main/resources/model/instance_call_number.json, src/main/resources/swagger.api/schemas/response/callNumberBrowseItem.yaml, src/test/java/org/folio/search/controller/BrowseCallNumberConsortiumIT.java, src/test/java/org/folio/search/controller/BrowseCallNumberIT.java, src/test/java/org/folio/search/controller/IndexingInstanceCallNumberIT.java, src/test/java/org/folio/search/service/consortium/ConsortiumSearchHelperTest.java, src/test/java/org/folio/search/service/reindex/jdbc/CallNumberRepositoryIT.java
Support showing instance title in the browse results list
Change index structure to include not `counts` but `instanceIds`. This change allows to fetch instance titles from the instance index. Counts are calculated on the fly during conversion by counting instance ids. Add filtering `instances` objects by `locationId` filter.
https://folio-org.atlassian.net/browse/MSEARCH-948
=> feat(cn-browse): support showing instance title in browse results list

NEWS.md, src/main/java/org/folio/search/service/reindex/ReindexService.java
Fix issue with using member tenant postgres schema on reindexing
- Add user tenants cache eviction on full reindex service call
[MSEARCH-957](https://folio-org.atlassian.net/browse/MSEARCH-957)
=> fix(reindex): Fix issue with using member tenant postgres schema on reindexing

descriptors/ModuleDescriptor-template.json
Fix issue when User with permission “Inventory: View instances, holdings, and items” doesn't have access to call numbers browse
Assign correct permissions to endpoints
https://folio-org.atlassian.net/browse/MSEARCH-965
=> fix(cn-browse): fix permissions

NEWS.md, src/main/java/org/folio/search/cql/searchterm/NoSpaceSearchTermProcessor.java, src/main/java/org/folio/search/service/lccn/NoSpaceNormalizer.java, src/main/java/org/folio/search/service/lccn/StringNormalizer.java, src/main/java/org/folio/search/service/setter/AbstractLccnProcessor.java, src/main/java/org/folio/search/service/setter/authority/LccnAuthorityProcessor.java, src/main/java/org/folio/search/service/setter/instance/LccnInstanceProcessor.java, src/main/java/org/folio/search/service/setter/linkeddata/common/LinkedDataClassificationAdditionalNumberProcessor.java, src/main/java/org/folio/search/service/setter/linkeddata/common/LinkedDataClassificationNumberProcessor.java, src/main/java/org/folio/search/service/setter/linkeddata/instance/LinkedDataInstanceClassificationAdditionalNumberProcessor.java, src/main/java/org/folio/search/service/setter/linkeddata/instance/LinkedDataInstanceClassificationNumberProcessor.java, src/main/java/org/folio/search/service/setter/linkeddata/work/LinkedDataWorkClassificationAdditionalNumberProcessor.java, src/main/java/org/folio/search/service/setter/linkeddata/work/LinkedDataWorkClassificationNumberProcessor.java, src/main/resources/model/authority.json, src/main/resources/model/instance.json, src/main/resources/model/linked_data_instance.json, src/main/resources/model/linked_data_work.json, src/main/resources/swagger.api/examples/result/linkedDataInstanceSearchResult.yaml, src/main/resources/swagger.api/examples/result/linkedDataWorkSearchResult.yaml, src/main/resources/swagger.api/schemas/dto/linked-data/common/linkedDataClassification.yaml, src/main/resources/swagger.api/schemas/dto/linked-data/common/linkedDataWorkOnly.yaml, src/test/java/org/folio/search/controller/SearchLinkedDataInstanceIT.java, src/test/java/org/folio/search/controller/SearchLinkedDataWorkIT.java, src/test/java/org/folio/search/cql/searchterm/NoSpaceSearchTermProcessorTest.java, src/test/java/org/folio/search/service/lccn/NoSpaceNormalizerTest.java, src/test/java/org/folio/search/service/setter/authority/LccnAuthorityProcessorTest.java, src/test/java/org/folio/search/service/setter/instance/LccnInstanceProcessorTest.java, src/test/java/org/folio/search/utils/LinkedDataTestUtils.java, src/test/resources/samples/linked-data/instance.json, src/test/resources/samples/linked-data/work.json
Linked Data Instance and Work: search by classification type/number/additionalNumber
Existed Linked Data model and DTO extended with few additional fields
https://folio-org.atlassian.net/browse/MSEARCH-989
=> MSEARCH-989: Linked Data Instance and Work: search by classification type/number/additionalNumber

NEWS.md, src/main/java/org/folio/search/cql/FacetQueryBuilder.java, src/test/java/org/folio/api/browse/BrowseCallNumberConsortiumIT.java
Filtering by one of facet in call-number browse, doesn't have affect to other facets.
adjust facet filtering for nested queries
https://folio-org.atlassian.net/browse/MSEARCH-1012
=> fix: adjust facet filtering for nested queries

NEWS.md, src/main/resources/model/authority.json
With the increase of the number of headings the keyword search becomes unachievable as now it searches by all heading fields. In this case the generated elastic search query contains more boolean clauses than it is allowed  - regulated with setting and default value: maxClauseCount = 1024
introduce new generated search field for keyword search which would represent all headings
[MSEARCH-1020](https://folio-org.atlassian.net/browse/MSEARCH-1020)
=> MSEARCH-1020: Authority Search: Fix keyword search by all heading fields  

NEWS.md, src/main/java/org/folio/search/service/consortium/ConsortiumInstanceSearchService.java
Fix the issue when the consortium batch search returns fewer results for duplicate identifiers
Change `size` in search request
https://folio-org.atlassian.net/browse/MSEARCH-804
=> fix(consortium-search): batch search returns less results for duplicate identifiers
